library(NominalLogisticBiplot)


### Name: Generators
### Title: Generators (points) of the tesselation generated by a nominal
###   variable.
### Aliases: Generators
### Keywords: tesselations invert voronoi

### ** Examples

  data(HairColor)
  data = data.matrix(HairColor)
  xEM = NominalLogBiplotEM(data, dim = 2,showResults = FALSE)
  nomreg = polylogist(data[,2],xEM$RowCoordinates[,1:2],penalization=0.1)
  tesselation = Generators(nomreg$beta)
  tesselation



