library(cna)


### Name: some
### Title: Randomly select configurations from a data frame or 'truthTab'
### Aliases: some some.data.frame some.truthTab

### ** Examples

# Randomly sample configurations from the dataset analyzed by Krook (2010).
tt.women <- truthTab(d.women)
some(tt.women, 20)
some(tt.women, 5, replace = FALSE)
some(tt.women, 5, replace = TRUE)

# Simulate limited diversity in data generated by the causal structure 
# A=2*B=1 + C=3*D=4 <-> E=3.
dat1 <- allCombs(c(3, 3, 4, 4, 3))
dat2 <- selectCases("A=2*B=1 + C=3*D=4 <-> E=3", dat1, type = "mv")
(dat3 <- some(dat2, 150, replace = TRUE))
mvcna(dat3)

# Simulate large-N fuzzy-set data generated by the common-cause structure
# (A*b*C + B*c <-> D) * (A*B + a*C <-> E).
dat1 <- allCombs(c(2, 2, 2, 2, 2)) - 1
dat2 <- selectCases("(A*b*C + B*c <-> D) * (A*B + a*C <-> E)", dat1)
dat3 <- some(dat2, 250, replace = TRUE)
dat4 <- makeFuzzy(tt2df(dat3), fuzzvalues = seq(0, 0.45, 0.01))
fscna(dat4, ordering = list(c("D", "E")), strict = TRUE, con = .8, cov = .8)



