library(RcmdrPlugin.KMggplot2)


### Name: dataLine
### Title: A Dummy Data for Line Charts
### Aliases: dataLine
### Keywords: data

### ** Examples

# This data is generated by the code below:
# set.seed(5435678)
# date <- rep(seq(Sys.Date(), len = 12, by = "1 month"), each = 12)
# group <- rep(c("T", "H", "L"), 12, each = 4)
# marker <- factor(rep(c("High", "Low"), 36, each = 2))
# sex <- factor(rep(c("M", "F"), 72))
# mu <- rep(c(200, 50, 150), 12, each = 4) + 10 * as.numeric(sex) + 30 * as.numeric(marker)
# y <- rnorm(144, mu, 25)
# dataLine <- data.frame(date, group, marker, sex, y)
# save(dataLine, file = "dataLine.RData")
# try(data(dataLine, package = "RcmdrPlugin.KMggplot2"))



