library(RcmdrPlugin.KMggplot2)


### Name: dataContour
### Title: A Dummy Data for Contour Plots
### Aliases: dataContour
### Keywords: data

### ** Examples

# This data is generated by the code below:
# set.seed(5435678)
# dataContour <- data.frame(
#   x = (zx <- (rep(1:100, 100) - 5) / 2),
#   y = (zy <- (rep(1:100, each=100) - 5) / 2),
#   z = (z  <- zx*zy)
# )
# save(dataContour, file = "dataContour.RData")
# try(data(dataContour, package = "RcmdrPlugin.KMggplot2"))



