library(inline)


### Name: getDynLib-methods
### Title: Retrieve the dynamic library (or DLL) associated with a package
###   of a function generated by cfunction
### Aliases: getDynLib getDynLib-methods getDynLib,CFunc-method
###   getDynLib,character-method getDynLib,CFuncList-method
### Keywords: methods

### ** Examples

## Not run: 
##D getDynLib( "base" )
##D 
##D f <- cfunction( signature() , "return R_NilValue ;" )
##D getDynLib( f )
##D 
## End(Not run)


