library(ecolottery)


### Name: forward
### Title: Simulation of neutral and niche-based community dynamics forward
###   in time
### Aliases: forward get_number_of_gens pick pick.mutate pick.immigrate
### Keywords: neutral dynamics niche-based dynamics

### ** Examples

## Not run: 
##D # Initial community composed of 10 species each including 10 individuals
##D initial1 <- rep(as.character(1:10), each = 10)
##D 
##D # Simulation of speciation and drift dynamics over 100 time steps
##D final1 <- forward(initial = initial1, prob = 0.1, gens = 1000)
##D # The final community includes new species (by default names begins with "new")
##D final1$com$sp # includes new species generated by speciation events
##D 
##D # A regional pool including 100 species each including 10 individuals
##D pool <- rep(as.character(1:100), each = 10)
##D 
##D # Simulation of migration and drift dynamics over 1000 time steps
##D final2 <- forward(initial = initial1, prob = 0.1, gens = 1000, pool = pool)
##D # The final community includes species that have immigrated from the pool
##D final2$com$sp # includes new species that immigrated from the pool
##D 
##D # Initial community composed of 10 species each including 10 individuals, 
##D # with trait information for niche-based dynamics
##D initial2 <- data.frame(sp = rep(as.character(1:10), each = 10), 
##D                       trait = runif(100))
##D 
##D # Simulation of stabilizing hab. filtering around t = 0.5, over 1000 time steps
##D sigm <- 0.1
##D filt_gaussian <- function(t,x) exp(-(x - t)^2/(2*sigm^2))
##D final3 <- forward(initial = initial2, prob = 0.1, gens = 1000, pool = pool, 
##D                  filt = function(x) filt_gaussian(0.5,x))
##D plot_comm(final3) # trait distribution in final community
##D 
##D # With higher immigration
##D final4 <- forward(initial = initial2, prob = 0.8, gens = 1000, pool = pool, 
##D                  filt = function(x) filt_gaussian(0.5,x))
##D plot_comm(final4) # should be closer to 0.5
##D 
##D # Simulation of limiting similarity, over 1000 time steps
##D final5 <- forward(initial = initial2, prob = 0.1, gens = 1000, pool = pool, 
##D                  limit.sim = TRUE)
##D plot_comm(final5)
##D 
##D # Stronger limiting similarity
##D final6 <- forward(initial = initial2, prob = 0.1, gens = 1000, pool = pool, 
##D                  limit.sim = TRUE, coeff.lim.sim = 20)
##D plot_comm(final6) # the distribution will be more even
##D 
##D # Variation of community richness with time
##D final7 <- forward(initial = initial2, prob = 0.1, gens = 1000, pool = pool, 
##D                  limit.sim = TRUE, keep = TRUE, plot_gens = TRUE)
##D 
##D # Check stationarity
##D plot(unlist(lapply(final7$com_t, function(x) length(unique(x[, 2])))), 
##D      xlab = "Time step", ylab = "Community richness") 
##D 
##D # Index of limiting similarity over time
##D plot(final7$dist.t, xlab = "Time step", ylab = "Limiting similarity")
## End(Not run)



