library(vortexR)


### Name: collate_proc_data
### Title: Collate processed data generated by any of the 'collate'
###   functions
### Aliases: collate_proc_data

### ** Examples

# Using Campbell et al. example data. See ?sta.main, ?sta.evy5, ?sta.evy5.b11
# for more details.
data(sta.main, sta.evy5, sta.evy5.b11)
dfs <- list(sta.main, sta.evy5, sta.evy5.b11)
combined <- collate_proc_data(dfs, save2disk=FALSE)



