library(pompom)


### Name: plot_time_profile
### Title: Plot time profiles given a time-series generated by impulse
###   response analysis
### Aliases: plot_time_profile

### ** Examples

## Don't show: 
plot_time_profile(time.series.data = bootstrap_iRAM_2node$time.profile.data,
                 var.number = 2,
                 threshold= .01,
                 xupper = 20)
## End(Don't show)

## No test: 
plot_time_profile(time.series.data = bootstrap_iRAM_2node$time.profile.data,
                 var.number = 2,
                 threshold= .01,
                 xupper = 20)
## End(No test)




