library(semPLS)


### Name: read.splsm
### Title: Import of XML Model Description Specified in SmartPLS
### Aliases: read.splsm

### ** Examples

# getting the path to file: 'ECSI_Tenenhaus.splsm' (generated by SmartPLS)
ptf <- system.file("SmartPLS", "workspace", "ecsi", "ECSI_Tenenhaus.splsm",
                   package="semPLS")

# creating the model specification to use with 'sempls()'.
ECSI <- read.splsm(ptf)
ECSI



