library(naniar)


### Name: cast_shadow_shift_label
### Title: Add a shadow column and a shadow shifted column to a dataset
### Aliases: cast_shadow_shift_label

### ** Examples


airquality %>% cast_shadow_shift_label(Ozone)
airquality %>% cast_shadow_shift_label(Ozone, Solar.R)

# replicate the plot generated by geom_miss_point()

library(ggplot2)

airquality %>%
  cast_shadow_shift_label(Ozone,Solar.R) %>%
  ggplot(aes(x = Ozone_shift,
             y = Solar.R_shift,
             colour = any_missing)) +
        geom_point()




