library(datarobot)


### Name: GetRulesets
### Title: List the rulesets approximating a model generated by DataRobot
###   Prime
### Aliases: GetRulesets

### ** Examples

## Not run: 
##D   projectId <- "59a5af20c80891534e3c2bde"
##D   modelId <- "5996f820af07fc605e81ead4"
##D   GetRulesets(projectId, modelId)
## End(Not run)



