library(repfdr)


### Name: zmat_sim
### Title: Simulated data set
### Aliases: zmat_sim
### Keywords: datasets Replicability GWAS

### ** Examples

data(zmat_sim)
head(zmat_sim)

## Not run: 
##D   input.to.repfdr <- ztobins(zmat_sim, 2 )
##D   pbz_sim1 <- input.to.repfdr$pdf.binned.z
##D   bz_sim1  <- input.to.repfdr$binned.z.mat
##D   
##D   data(binned_zmat_sim)
##D   stopifnot(all.equal(pbz_sim1,pbz_sim))
##D   stopifnot(all.equal(bz_sim1,bz_sim))
## End(Not run)

#### zmat_sim was generated by the following code:
data(hmat_sim)
set.seed(12)
m <- nrow(hmat_sim)
zmat_sim1  <- matrix(rnorm(n=3*m,mean=hmat_sim*3),nrow=m,ncol=3)
data(zmat_sim)
stopifnot(all.equal(zmat_sim1,zmat_sim))



