library(stacomirtools)


### Name: RequeteODBC-class
### Title: Class "RequeteODBC"
### Aliases: RequeteODBC-class RequeteODBC
### Keywords: classes

### ** Examples

showClass("RequeteODBC")
## Not run: 
##D  object=new("RequeteODBC")
##D  object@open=TRUE 
##D  ## this will leave the connection open, 
##D  ## by default it closes after the query is sent
##D  ## the following will work only if you have configured and 'ODBC' link
##D  object@baseODBC=c("myODBCconnection","myusername","mypassword")
##D  object@sql= "select * from mytable limit 100"
##D  object<-connect(object)
##D  odbcClose(object@connection)
##D  envir_stacomi=new.env()
##D  ## While testing I like to see the output of sometimes complex queries generated by the program
##D  assign("showmerequest",1,envir_stacomi) 
##D  ## You can assign any values (here 1)
##D  ## just tests the existence of "showmerequest" in envir_stacomi
##D  object=new("RequeteODBC")
##D  object@baseODBC=c("myODBCconnection","myusername","mypassword")
##D  object@sql= "select * from mytable limit 100"
##D  object<-connect(object)
##D ## the connection is already closed, the query is printed
## End(Not run)



