library(MTDrh)


### Name: EPI
### Title: Wind power scenarios generated by epi-spline approximation
### Aliases: EPI
### Keywords: datasets

### ** Examples

data(EPI)
epi_ranks <- MTDrh(EPI$scen,EPI$obs,EPI$prob,FALSE,FALSE)

#with different probabilities;
s.prob<-array(rep(c(0.7,rep(0.3/26,times=26)),times=345),dim=c(27,345))
epi_ranks <- MTDrh(EPI$scen,EPI$obs,s.prob,FALSE,FALSE)
  
#or
s.prob2<-array(rep(c(0.35,rep(0.3/25,times=25),0.35),times=345),dim=c(27,345))
epi_ranks <- MTDrh(EPI$scen,EPI$obs,s.prob2,FALSE,FALSE)
  



