library(MTDrh)


### Name: QR
### Title: Wind power scenarios generated by Quantile Regression with
###   Gaussian copula approach
### Aliases: QR
### Keywords: datasets

### ** Examples

data(QR)
qr_ranks <- MTDrh(QR$scen,QR$obs,NULL,FALSE,FALSE)



