library(RHPCBenchmark)


### Name: RunDenseMatrixBenchmark
### Title: Runs all of the dense matrix microbenchmarks
### Aliases: RunDenseMatrixBenchmark

### ** Examples

## Not run: 
##D # Set needed environment variables for multithreading.  Only single threading
##D # is used in the example.
##D #
##D # Note: The environment variables are usually set by the user before starting
##D #       the R programming environment; they are set here only to facilitate
##D #       a working example.  See the section on multithreading in the vignette
##D #       for further details.
##D Sys.setenv(R_BENCH_NUM_THREADS_VARIABLE="MKL_NUM_THREADS")
##D Sys.setenv(MKL_NUM_THREADS="1")
##D #
##D # Generate example microbechmarks that can be run in a few minutes; see
##D # the vignette for more involved examples.  The Cholesky factorization and
##D # matrix crossproduct microbenchmarks are performed in the example code
##D # below.
##D #
##D # Note: These microbenchmarks are different than the microbenchmarks
##D #       generated by \code{GetDenseMatrixDefaultMicrobenchmarks}.
##D #       They are chosen for their short run times and suitability for
##D #       example code. 
##D exampleMicrobenchmarks <- GetDenseMatrixExampleMicrobenchmarks()
##D # Set the output directory of the CSV summary results files
##D resultsDirectory <- "./DenseMatrixExampleOutput"
##D # Create the output directory
##D dir.create(resultsDirectory)
##D # Set an appropriate run identifier
##D runIdentifier <- "example"
##D resultsFrame <- RunDenseMatrixBenchmark(runIdentifier, resultsDirectory,
##D    microbenchmarks=exampleMicrobenchmarks)
##D 
##D # This example runs all but the matrix transpose microbenchmarks.
##D exampleMicrobenchmarks[["transpose"]]$active <- FALSE
##D # Set an appropriate run identifier
##D runIdentifier <- "no_transpose"
##D exTransposeResultsFrame <- RunDenseMatrixBenchmark(runIdentifier,
##D   resultsDirectory, microbenchmarks=exampleMicrobenchmarks)
##D 
##D # This example runs only the matrix-matrix multiplication microbenchmark,
##D # and it adds a larger matrix to test.
##D matMatMicrobenchmark <- list()
##D matMatMicrobenchmark[["matmat"]] <- GetDenseMatrixExampleMicrobenchmarks()[["matmat"]]
##D matMatMicrobenchmark[["matmat"]]$dimensionParameters <- as.integer(c(1000, 2000))
##D matMatMicrobenchmark[["matmat"]]$numberOfTrials <- as.integer(c(3, 3))
##D matMatMicrobenchmark[["matmat"]]$numberOfWarmupTrials <- as.integer(c(1, 1))
##D # Set an appropriate run identifier
##D runIdentifier <- "matmat"
##D matMatResults <- RunDenseMatrixBenchmark(runIdentifier, resultsDirectory,
##D    microbenchmarks=matMatMicrobenchmark)
## End(Not run)




