library(RHPCBenchmark)


### Name: RunMachineLearningBenchmark
### Title: Runs all of the machine learning microbenchmarks
### Aliases: RunMachineLearningBenchmark

### ** Examples

## Not run: 
##D # Set needed environment variables for multithreading.  Only single threading
##D # is used in the example.
##D #
##D # Note: The environment variables are usually set by the user before starting
##D #       the R programming environment; they are set here only to facilitate
##D #       a working example.  See the section on multithreading in the vignette
##D #       for further details.
##D Sys.setenv(R_BENCH_NUM_THREADS_VARIABLE="MKL_NUM_THREADS")
##D Sys.setenv(MKL_NUM_THREADS="1")
##D #
##D # Generate example microbechmarks that can be run in a few minutes; see
##D # the vignette for more involved examples. Clustering microbenchmarks
##D # are defined in the examples.
##D #
##D # Note: These microbenchmarks are different than the microbenchmarks
##D #       generated by \code{GetDenseMatrixDefaultMicrobenchmarks}.
##D #       They are chosen for their short run times and suitability for
##D #       example code. 
##D exampleMicrobenchmarks <- GetClusteringExampleMicrobenchmarks()
##D # Set the output directory of the CSV summary results files
##D resultsDirectory <- "./MachineLearningExampleOutput"
##D # Create the output directory
##D dir.create(resultsDirectory)
##D # Set an appropriate run identifier
##D runIdentifier <- "example"
##D resultsFrame <- RunMachineLearningBenchmark(runIdentifier, resultsDirectory,
##D    clusteringMicrobenchmarks=exampleMicrobenchmarks)
##D 
##D # Create a new clustering microbenchmark that tests the clara method from
##D # the cluster package using a data set with 16 features, 8 clusters, and
##D # 1000 normally distributed feature vectors per cluster. 
##D claraMicrobenchmark <- list()
##D claraMicrobenchmark[["clara_cluster_16_8_1000"]] <- methods::new(
##D    "ClusteringMicrobenchmark",
##D    active = TRUE,
##D    benchmarkName = "clara_cluster_16_8_1000",
##D    benchmarkDescription = "Example of new clara microbenchmark",
##D    dataObjectName = NA_character_,
##D    numberOfFeatures = as.integer(16),
##D    numberOfClusters = as.integer(8),
##D    numberOfFeatureVectorsPerCluster = as.integer(1000),
##D    numberOfTrials = as.integer(3),
##D    numberOfWarmupTrials = as.integer(1),
##D    allocatorFunction = ClusteringAllocator,
##D    benchmarkFunction = ClaraClusteringMicrobenchmark
##D )
##D 
##D # Set an appropriate run identifier
##D runIdentifier <- "clara_new"
##D # Run the clara microbenchmark
##D claraResults <- RunMachineLearningBenchmark(runIdentifier, resultsDirectory,
##D    clusteringMicrobenchmarks=claraMicrobenchmark)
## End(Not run)




