library(RHPCBenchmark)


### Name: RunSparseMatrixBenchmark
### Title: Runs all of the sparse matrix microbenchmarks
### Aliases: RunSparseMatrixBenchmark

### ** Examples

## Not run: 
##D # Set needed environment variables for multithreading.  Only single threading
##D # is used in the example.
##D #
##D # Note: The environment variables are usually set by the user before starting
##D #       the R programming environment; they are set here only to facilitate
##D #       a working example.  See the section on multithreading in the vignette
##D #       for further details.
##D Sys.setenv(R_BENCH_NUM_THREADS_VARIABLE="MKL_NUM_THREADS")
##D Sys.setenv(MKL_NUM_THREADS="1")
##D #
##D # Generate example microbenchmarks that can be run in a few minutes; see
##D # the vignette for more involved examples.  The matvec_laplacian7pt_100
##D # and cholesky_ct20stif microbenchmarks are defined in the examples.
##D #
##D # Note: The example microbenchmarks are different than the microbenchmarks
##D #       generated by
##D #       \code{GetSparseMatrixVectorDefaultMicrobenchmarks},
##D #       \code{GetSparseCholeskyDefaultMicrobenchmarks},
##D #       \code{GetSparseLuDefaultMicrobenchmarks}, and
##D #       \code{GetSparseQrDefaultMicrobenchmarks};
##D #       they were chosen for their short run times and suitability for
##D #       example code. 
##D exampleMatrixVectorMicrobenchmarks <- GetSparseMatrixVectorExampleMicrobenchmarks()
##D exampleCholeskyMicrobenchmarks <- GetSparseCholeskyExampleMicrobenchmarks()
##D # Set the output directory of the CSV summary results files
##D resultsDirectory <- "./SparseMatrixExampleOutput"
##D # Create the output directory
##D dir.create(resultsDirectory)
##D # Set an appropriate run identifier
##D runIdentifier <- "example"
##D # Run only the matrix-vector and Cholesky factorization microbenchmarks, as
##D # the others take a long time
##D resultsFrame <- RunSparseMatrixBenchmark(runIdentifier, resultsDirectory,
##D    matrixVectorMicrobenchmarks=exampleMatrixVectorMicrobenchmarks,
##D    choleskyMicrobenchmarks=exampleCholeskyMicrobenchmarks,
##D    luMicrobenchmarks=NULL,
##D    qrMicrobenchmarks=NULL)
##D 
##D # This example runs only the Cholesky factorization microbenchmarks.
##D runIdentifier <- "choleksy_only"
##D # Run only the sparse Choleksy factorization microbenchmarks
##D choleskyResults <- RunSparseMatrixBenchmark(runIdentifier, resultsDirectory,
##D    matrixVectorMicrobenchmarks=NULL, luMicrobenchmarks=NULL,
##D    qrMicrobenchmarks=NULL)
##D 
## End(Not run)




