library(zTree)


### Name: zTreeSbj
### Title: Read '.sbj' files generated by 'z-Tree' into R
### Aliases: zTreeSbj
### Keywords: data manip

### ** Examples

## Not run: 
##D files <- list.files(pattern = "*.sbj$",recursive=TRUE)
##D fname <- sub(".*/","",files)
##D sbj <- zTreeSbj(aggregate(files,list(fname),function(x) x[1])$x)
## End(Not run)


