library(zTree)


### Name: zTreeTables
### Title: Read '.xls' files generated by 'z-Tree' into R
### Aliases: zTreeTables
### Keywords: data manip

### ** Examples

## Not run: 
##D zTT <- zTreeTables(c("080712_1412.xls","080712_1818.xls"))
##D with(zTT$subjects, table(Treatment,Period))
##D To read all tables from all sessions in directories below the current one:
##D sessions<-list.files(".","[0-9]{6}_[0-9]{4}.xls",recursive=TRUE)
##D zTT<-zTreeTables(sessions,tables=NULL)
## End(Not run)


