library(cutpointr)


### Name: cutpoint
### Title: Extract the cutpoints from a ROC curve generated by cutpointr
### Aliases: cutpoint cutpoints

### ** Examples

oc <- cutpointr(suicide, dsi, suicide, gender)
plot_cutpointr(oc, cutpoint, accuracy)




