library(sumFREGAT)


### Name: gene-based test functions
### Title: Gene-based tests on summary statistics
### Aliases: SKAT SKATO sumchi BT PCA FLM MLR simpleM minp

### ** Examples


# Using example score files "CFH.scores.vcf.gz" and "CFH.scores.full.vcf.gz"
# generated by prep.score.files() function (see examples for prep.score.files())

# Tests available with minimal input (P values and rsID):

score.file <- system.file("testfiles/CFH.scores.vcf.gz", package = "sumFREGAT")
cor.path <- system.file("testfiles/", package = "sumFREGAT")

sumchi(score.file, genes = "CFH", cor.path = cor.path)
simpleM(score.file, genes = "CFH", cor.path = cor.path)
minp(score.file, genes = "CFH", cor.path = cor.path)

# Tests available with full input including P values, rsID, betas,
# effect allele and allele frequencies (for default weighting):

score.file <- system.file("testfiles/CFH.scores.full.vcf.gz", package = "sumFREGAT")
cor.path <- system.file("testfiles/", package = "sumFREGAT")

sumchi(score.file, genes = "CFH", cor.path = cor.path)
simpleM(score.file, genes = "CFH", cor.path = cor.path)
minp(score.file, genes = "CFH", cor.path = cor.path)
BT(score.file, genes = "CFH", cor.path = cor.path)
SKAT(score.file, genes = "CFH", cor.path = cor.path)
SKATO(score.file, genes = "CFH", cor.path = cor.path)

# Tests that require sample size to be provided as "n" argument:

PCA(score.file, genes = "CFH", cor.path = cor.path, n = 85)
FLM(score.file, genes = "CFH", cor.path = cor.path, n = 85)
MLR(score.file, genes = "CFH", cor.path = cor.path, n = 85)




