library(MplusAutomation)


### Name: getSavedata_Fileinfo
### Title: Read Variable Names, Formats, and Widths from data generated by
###   the SAVEDATA Command
### Aliases: getSavedata_Fileinfo
### Keywords: interface

### ** Examples

## Not run: 
##D   fileInfo <- getSavedata_Fileinfo("C:/Program Files/Mplus/Test Output.out")
## End(Not run)



