library(PanJen)


### Name: plotff
### Title: This function plots objects generated by choose.fform or fform
### Aliases: plotff

### ** Examples


library(PanJen) 
data("hvidovre")

form<-formula(lprice ~brick+roof_tile+roof_cemen+rebuild90+rebuild00+y7+y8+y9) 
PanJenArea<-fform(data=hvidovre,variable="area",base_form=form) 
plotff(PanJenArea) 



