library(OmicKriging)


### Name: read_GRMBin
### Title: Read the GRM binary file.
### Aliases: read_GRMBin

### ** Examples

  ## read binary Genetic Relatedness Matrix (GRM) generated by GCTA
  grmFile <- system.file(package = "OmicKriging",
                         "doc/vignette_data/ig_genotypes.grm.bin")
  grmFileBase <- substr(grmFile,1, nchar(grmFile) - 4)
  GRM <- read_GRMBin(grmFileBase)



