library(CP)


### Name: ConPwrExpAndersen
### Title: Conditional Power (Exponential (Andersen))
### Aliases: ConPwrExpAndersen

### ** Examples

 # data frame 'test' generated by 'GenerateDataFrame'
 
 # conditional power calculations
 # within the exponential model
 # with the original formulae of the Andersen paper
 ConPwrExpAndersen(data = test, cont.time = 12, new.pat = c(2.5, 2.5),
                   theta.0 = 0.75, alpha = 0.05,
                   disp.data = TRUE, plot.km = TRUE)



