library(CP)


### Name: ConPwrNonMixWei
### Title: Conditional Power (Non-Mixture-Weibull)
### Aliases: ConPwrNonMixWei

### ** Examples

 # data frame 'test' generated by 'GenerateDataFrame'
 
 # conditional power calculations
 # within the non-mixture model with Weibull type survival
 ConPwrNonMixWei(data = test, cont.time = 12, new.pat = c(2.5, 2.5),
                 theta.0 = 0.75, alpha = 0.05,
                 disp.data = TRUE, plot.km = TRUE)



