library(CP)


### Name: ConPwrNonMixExp
### Title: Conditional Power (Non-Mixture-Exponential)
### Aliases: ConPwrNonMixExp

### ** Examples

 # data frame 'test' generated by 'GenerateDataFrame'
 
 # conditional power calculations
 # within the non-mixture model with exponential survival
 ConPwrNonMixExp(data = test, cont.time = 12, new.pat = c(2.5, 2.5),
                 theta.0 = 0.75, alpha = 0.05,
                 disp.data = TRUE, plot.km = TRUE)



