library(CP)


### Name: ConPwrNonMixGamma
### Title: Conditional Power (Non-Mixture-Gamma)
### Aliases: ConPwrNonMixGamma

### ** Examples

 # data frame 'test' generated by 'GenerateDataFrame'
 
 # conditional power calculations
 # within the non-mixture model with Gamma type survival
 ConPwrNonMixGamma(data = test, cont.time = 12, new.pat = c(2.5, 2.5),
                   theta.0 = 0.75, alpha = 0.05,
                   disp.data = TRUE, plot.km = TRUE)



