library(drake)


### Name: Makefile_recipe
### Title: For 'make(..., parallelism = "Makefile")', see what your
###   'Makefile' recipes will look like in advance.
### Aliases: Makefile_recipe

### ** Examples

# Only relevant for "Makefile" parallelism.
# Show an example Makefile recipe.
Makefile_recipe(cache_path = "path") # `cache_path` has a reliable default.
# Customize your Makefile recipe.
Makefile_recipe(
  target = "this_target",
  recipe_command = "R -e 'R_RECIPE' -q",
  cache_path = "custom_cache"
)
default_recipe_command() # "Rscript -e 'R_RECIPE'" # nolint
r_recipe_wildcard() # "R_RECIPE"
## Not run: 
##D test_with_dir("Quarantine side effects.", {
##D load_mtcars_example() # Get the code with drake_example("mtcars").
##D # Look at the Makefile generated by the following.
##D # make(my_plan, paralleliem = "Makefile") # Requires Rtools on Windows. # nolint
##D # Generates a Makefile with "R -q -e" rather than
##D # "Rscript -e".
##D # Be aware the R -q -e fails on Windows.
##D # make(my_plan, parallelism = "Makefile", jobs = 2, # nolint
##D #   recipe_command = "R -q -e") # nolint
##D # Same thing:
##D clean() # Start from scratch.
##D # make(my_plan, parallelism = "Makefile", jobs = 2, # nolint
##D #   recipe_command = "R -q -e 'R_RECIPE'") # nolint
##D clean() # Start from scratch.
##D # make(my_plan, parallelism = "Makefile", jobs = 2, # nolint
##D #   recipe_command = "R -e 'R_RECIPE' -q") # nolint
##D })
## End(Not run)



