library(P2C2M)


### Name: p2c2m.complete
### Title: Execute the complete P2C2M pipeline via a single command
### Aliases: p2c2m.complete

### ** Examples

## Example of the minimal data requirements to run P2C2M

# The absolute path to the input directory is set
inPath <- system.file("extdata", "sim.E.003.small/", package="P2C2M")

# The name of the xml-file generated by BEAUTi and located in 
# "inPath" is set
inFile <- "sim.E.003.small.xml"

# Posterior predictive simulations with a setting of 2 simulation 
# replicates are preformed
sim.E.003.small <- p2c2m.complete(inPath, inFile, num.reps=2, save.metadata=TRUE)



