library(clinDR)


### Name: print.emaxsimobj
### Title: Print a data set generated by emaxsim
### Aliases: print.emaxsimobj
### Keywords: nonlinear

### ** Examples


## Not run: 
##D 
##D save.seed<-.Random.seed
##D set.seed(12357)
##D 
##D nsim<-50
##D idmax<-5
##D doselev<-c(0,5,25,50,100)
##D n<-c(78,81,81,81,77)
##D 
##D ### population parameters for simulation
##D e0<-2.465375 
##D ed50<-67.481113 
##D emax<-15.127726
##D sdy<-7.967897
##D pop<-c(log(ed50),emax,e0)    
##D meanlev<-emaxfun(doselev,pop)  
##D 
##D ###FixedMean is specialized constructor function for emaxsim
##D gen.parm<-FixedMean(n,doselev,meanlev,sdy)  
##D D1 <- emaxsim(nsim,gen.parm)
##D e49<-D1[49]
##D 
##D e49
##D 
##D print(e49,c(101,200))  
##D 
##D .Random.seed<-save.seed
## End(Not run)



