library(tidyLPA)


### Name: get_estimates
### Title: Get estimates from objects generated by tidyLPA
### Aliases: get_estimates get_estimates.tidyLPA get_estimates.tidyProfile

### ** Examples

## Not run: 
##D if(interactive()){
##D  results <- iris %>%
##D    select(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) %>%
##D    estimate_profiles(3)
##D  get_estimates(results)
##D  get_estimates(results[[1]])
##D  }
## End(Not run)



