library(tidyLPA)


### Name: get_data
### Title: Get data from objects generated by tidyLPA
### Aliases: get_data get_data.tidyLPA get_data.tidyProfile

### ** Examples

## Not run: 
##D if(interactive()){
##D  results <- iris %>%
##D    select(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) %>%
##D    estimate_profiles(3)
##D  get_data(results)
##D  get_data(results[[1]])
##D  }
## End(Not run)



