library(tidyLPA)


### Name: get_fit
### Title: Get fit indices from objects generated by tidyLPA
### Aliases: get_fit get_fit.tidyLPA get_fit.tidyProfile

### ** Examples

## Not run: 
##D if(interactive()){
##D  results <- iris %>%
##D    select(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width) %>%
##D    estimate_profiles(3)
##D  get_fit(results)
##D  get_fit(results[[1]])
##D  }
## End(Not run)



