library(prevR)


### Name: fdhs
### Title: Fictitious data generated by a DHS simulation.
### Aliases: fdhs fdhs.boundary fdhs.clusters
### Keywords: datasets

### ** Examples

## Not run: 
##D   str(fdhs)
##D   str(fdhs.clusters)
##D   str(fdhs.boundary)
##D   demo(prevR)
## End(Not run) 



