library(ArchaeoPhases)


### Name: ImportCSV.BCal
### Title: Importing a BCal csv file
### Aliases: ImportCSV.BCal
### Keywords: CSV file

### ** Examples


  # Import of MCMC generated by BCal and extracted in cal BP (the year of reference is 1950)
  data(Fishpond)
  write.csv(Fishpond, "fishpond_MCMC.csv", row.names=FALSE)
  Fishpond = ImportCSV.BCal("fishpond_MCMC.csv", bin.width=1)
  # equivalent to 
  #Fishpond2 = ImportCSV("fishpond_MCMC.csv", dec = '.', sep=',',referenceYear = 1950, 
  #rowToWithdraw = "last", bin.width=1)



