library(ArchaeoPhases)


### Name: ImportCSV
### Title: Importing a CSV file containing the output of the MCMC algorithm
### Aliases: ImportCSV
### Keywords: CSV file

### ** Examples

  data(Events)
  write.csv(Events, "data.csv", row.names=FALSE)
  data = ImportCSV("data.csv", dec = '.', sep=',', comment.char='#', header = TRUE, 
  iterationColumn = 1)
  
  # Import of MCMC generated by BCal and extracted in cal BP (the year of reference is 1950)
  data(Fishpond)
  write.csv(Fishpond, "fishpond_MCMC.csv", row.names=FALSE)
  Fishpond = ImportCSV("fishpond_MCMC.csv", dec = '.', sep=',', header = TRUE, 
  iterationColumn = 1, referenceYear = 1950, rowToWithdraw = "last")



