library(RDML)


### Name: RDML.AsTable
### Title: Represents fields of 'RDML' object as 'data.frame'
### Aliases: RDML.AsTable
### Keywords: manip

### ** Examples

## Not run: 
##D ## internal dataset stepone_std.rdml (in 'data' directory)
##D ## generated by Applied Biosystems Step-One. Contains qPCR data.
##D library(chipPCR)
##D PATH <- path.package("RDML")
##D filename <- paste(PATH, "/extdata/", "stepone_std.rdml", sep ="")
##D stepone <- RDML$new(filename)
##D ## Mark fluorescense data which Cq > 30 and add quantities to
##D ## AsTable output.
##D ## Names for fluorescense data will contain sample name and react
##D ## positions
##D tab <- stepone$AsTable(
##D          name.pattern = paste(react$sample$id, react$position),
##D          add.columns = list(cq30 = if(data$cq >= 30) ">=30" else "<30",
##D          quantity = as.factor(sample[[react$sample$id]]$quantity$value))
##D          )
##D ## Show cq30 and quantities
##D tab[c("cq30", "quantity")]
##D ## Get fluorescence values for 'std' type samples
##D ## in format ready for ggplot function
##D library(dplyr)
##D fdata <- stepone$GetFData(
##D            filter(tab, sample.type == "std"),
##D            long.table = TRUE)
##D ## Plot fdata with colour by cq30 and shape by quantity
##D library(ggplot2)
##D ggplot(fdata, aes(x = cyc, y = fluor,
##D                   group = fdata.name,
##D                   colour = cq30,
##D                   shape = quantity)) +
##D                   geom_line() + geom_point()
## End(Not run)



