library(RDML)


### Name: RDML.GetFData
### Title: Gets fluorescence data vectors from 'RDML' object
### Aliases: RDML.GetFData
### Keywords: manip

### ** Examples

## Not run: 
##D ## internal dataset BioRad_qPCR_melt.rdml (in 'data' directory)
##D ## generated by Bio-Rad CFX96. Contains qPCR and melting data.
##D ## Import without splitting by targets/types and with
##D ## custom name pattern.
##D PATH <- path.package("RDML")
##D filename <- paste(PATH, "/extdata/", "BioRad_qPCR_melt.rdml", sep ="")
##D cfx96 <- RDML$new(filename)
##D ## Select melting fluorescence data with sample.type 'unkn'.
##D library(dplyr)
##D tab <- cfx96$AsTable()
##D fdata <- cfx96$GetFData(filter(tab, sample.type == "unkn"),
##D                         dp.type = "adp")
##D ## Show names for obtained fdata
##D colnames(fdata)
## End(Not run)



