library(RDML)


### Name: RDML
### Title: R6 class 'RDML' - contains methods to read and overview
###   fluorescence data from RDML v1.1 and v1.2 format files
### Aliases: RDML
### Keywords: Bio--Rad CFX96 IO LightCycler RDML StepOne file qPCR

### ** Examples

## EXAMPLE 1:
## internal dataset lc96_bACTXY.rdml (in 'data' directory)
## generated by Roche LightCycler 96. Contains qPCR data
## with four targets and two types.
## Import with default settings.
PATH <- path.package("RDML")
filename <- paste(PATH, "/extdata/", "lc96_bACTXY.rdml", sep ="")
lc96 <- RDML$new(filename)

tab <- lc96$AsTable(name.pattern = paste(sample[[react$sample$id]]$description,
                                         react$id$id), 
                    quantity = sample[[react$sample$id]]$quantity$value)
## Show dyes names
unique(tab$target.dyeId)
## Show types of the samples for dye 'FAM'
library(dplyr)
unique(filter(tab, target.dyeId == "FAM")$sample.type)

## Show template quantities for dye 'FAM' type 'std'#' 
## Not run: 
##D COPIES <- filter(tab, target.dyeId == "FAM", sample.type == "std")$quantity
##D ## Define calibration curves (type of the samples - 'std').
##D ## No replicates.
##D library(qpcR)
##D CAL <- modlist(lc96$GetFData(filter(tab,
##D                                     target.dyeId == "FAM", 
##D                                     sample.type == "std")),
##D                baseline="lin", basecyc=8:15)
##D ## Define samples to predict (first two samples with the type - 'unkn').
##D PRED <- modlist(lc96$GetFData(filter(tab, 
##D                                     target.dyeId == "FAM", 
##D                                     sample.type == "unkn")),
##D                baseline="lin", basecyc=8:15)
##D ## Conduct quantification.
##D calib(refcurve = CAL, predcurve = PRED, thresh = "cpD2",
##D       dil = COPIES)
## End(Not run)
## Not run: 
##D ## EXAMPLE 2:
##D ## internal dataset lc96_bACTXY.rdml (in 'data' directory)
##D ## generated by Roche LightCycler 96. Contains qPCR data
##D ## with four targets and two types.
##D ## Import with default settings.
##D library(chipPCR)                        
##D PATH <- path.package("RDML")
##D filename <- paste(PATH, "/extdata/", "lc96_bACTXY.rdml", sep ="")
##D lc96 <- RDML$new(filename)
##D 
##D tab <- lc96$AsTable(name.pattern = paste(sample[[react$sample$id]]$description,
##D                                          react$id$id), 
##D                     quantity = sample[[react$sample$id]]$quantity$value)
##D ## Show targets names
##D unique(tab$target)
##D ## Fetch cycle dependent fluorescence for HEX chanel
##D tmp <- lc96$GetFData(filter(tab, target == "bACT", sample.type == "std"))
##D ## Fetch vector of dillutions 
##D dilution <- filter(tab, target.dyeId == "FAM", sample.type == "std")$quantity
##D 
##D ## Use plotCurves function from the chipPCR package to 
##D ## get an overview of the amplification curves
##D plotCurves(tmp[,1], tmp[,-1])
##D par(mfrow = c(1,1))
##D ## Use inder function from the chipPCR package to 
##D ## calculate the Cq (second derivative maximum, SDM)
##D SDMout <- sapply(2L:ncol(tmp), function(i) {
##D   SDM <- summary(inder(tmp[, 1], tmp[, i]), print = FALSE)[2]
##D })
##D 
##D ## Use the effcalc function from the chipPCR package and 
##D ## plot the results for the calculation of the amplification
##D ## efficiency analysis.
##D plot(effcalc(dilution, SDMout), CI = TRUE)
## End(Not run)
## Not run: 
##D ## EXAMPLE 3:
##D ## internal dataset BioRad_qPCR_melt.rdml (in 'data' directory)
##D ## generated by Bio-Rad CFX96. Contains qPCR and melting data.
##D ## Import with custom name pattern.
##D PATH <- path.package("RDML")
##D filename <- paste(PATH, "/extdata/", "BioRad_qPCR_melt.rdml", sep ="")
##D cfx96 <- RDML$new(filename)
##D ## Use plotCurves function from the chipPCR package to 
##D ## get an overview of the amplification curves
##D library(chipPCR)
##D ## Extract all qPCR data 
##D tab <- cfx96$AsTable()
##D cfx96.qPCR <- cfx96$GetFData(tab)
##D plotCurves(cfx96.qPCR[,1], cfx96.qPCR[,-1], type = "l")
##D 
##D ## Extract all melting data 
##D cfx96.melt <- cfx96$GetFData(tab, dp.type = "mdp")
##D ## Show some generated names for samples.
##D colnames(cfx96.melt)[2L:5]
##D ## Select columns that contain
##D ## samples with dye 'EvaGreen' and have type 'pos'
##D ## using filtering by names.
##D cols <- cfx96$GetFData(filter(tab, grepl("pos_EvaGreen$", fdata.name)),
##D                        dp.type = "mdp")
##D ## Conduct melting curve analysis.
##D library(qpcR)
##D invisible(meltcurve(cols, fluos = 2:ncol(cols),
##D           temps = rep(1, ncol(cols) - 1)))
## End(Not run)



