library(CollessLike)


### Name: distribution
### Title: Plot the distribution of Colless-Like, Sackin and cophenetic
###   normalized balance indices under the alpha-gamma model and computes
###   the percentile of a tree from previous distributions.
### Aliases: distribution

### ** Examples

#The parameter folder contains the location of the database
#If not specified folder=getwd()

## Different ways to introduce the tree
#From a newick string
## No test: 
distribution("(1,2,3,4,5);",0.5,0.3,db.path=folder)
## End(No test)
## No test: 
distribution("(1,(2,(3,(4,5))));",0.5,0.3,db.path=folder)
## End(No test)

#From a phylo object
## No test: 
require(ape)
## End(No test)
## No test: 
random.tree = rtree(5,rooted=TRUE)
## End(No test)
## No test: 
distribution(random.tree,0.5,0.3,db.path=folder)
## End(No test)

#An example of a tree generated by the alpha-gamma model (igraph object)
## No test: 
a.g.tree = a.g.model(5,0.5,0.3)
## End(No test)
## No test: 
distribution(a.g.tree,0.5,0.3,db.path=folder)
## End(No test)

## Different indices data
# From our data base
## No test: 
distribution(a.g.tree,0.5,0.3,db.path=folder)
## End(No test)

# From a data.frame generated by 'indices.simulation'
# ('Repetitions' set as 10 for a fast example)
## No test: 
indices.data = indices.simulation(5,0.5,0.3,10)
## End(No test)
## No test: 
distribution(a.g.tree,0.5,0.3,set.indices=indices.data) 
## End(No test)

# Allow the function to do a new generation of data and compute their indices
## No test: 
distribution(a.g.tree,0.5,0.3,new.simulation=TRUE,repetitions=10)
## End(No test)
# WARNING! it might take a long time, it depends on the parameters 
# 'n' (number of leaves) and 'repetition' (number of repetitions)




