library(KRMM)


### Name: KRMM-package
### Title: Kernel Ridge Mixed Model
### Aliases: KRMM-package
### Keywords: package

### ** Examples


## Not run: 
##D 
##D library(KRMM)
##D 
##D ### SIMULATE DATA 
##D set.seed(123)
##D p=200
##D N=100
##D 
##D beta=rnorm(p, mean=0, sd=1.0)
##D X=matrix(runif(p*N, min=0, max=1), ncol=p, byrow=TRUE)  #X: covariates (i.e. predictors)
##D 
##D f=X%*%beta                    #f: data generating process (i.e. DGP)
##D E=rnorm(N, mean=0, sd=0.5)
##D 
##D Y=f+E                           #Y: observed response data
##D 
##D hist(f)
##D hist(beta)
##D Nb_train=floor((2/3)*N)
##D 
##D ###======================================================================###
##D ### CREATE TRAINING AND TARGET SETS FOR RESPONSE AND PREDICTOR VARIABLES ###
##D ###======================================================================###
##D 
##D Index_train=sample(1:N, size=Nb_train, replace=FALSE)
##D 
##D ### Covariates (i.e. predictors) for training and target sets
##D 
##D Predictors_train=X[Index_train, ]
##D Response_train=Y[Index_train]
##D 
##D Predictors_target=X[-Index_train, ]
##D True_value_target=f[-Index_train]    #True value (generated by DGP) we want to predict
##D 
##D ###=================================================================================###
##D ### PREDICTION WITH KERNEL RIDGE REGRESSION SOLVED WITHIN THE MIXED MODEL FRAMEWORK ### 
##D ###=================================================================================###
##D 
##D #Linear kernel
##D 
##D Linear_KRR_model_train = Kernel_Ridge_MM(Y_train=Response_train, 
##D  Matrix_covariates_train=Predictors_train, method="RR-BLUP")
##D 
##D f_hat_target_Linear_KRR = Predict_kernel_Ridge_MM( Linear_KRR_model_train,
##D  Matrix_covariates_target=Predictors_target )
##D 
##D #Gaussian kernel
##D 
##D Gaussian_KRR_model_train = Kernel_Ridge_MM( Y_train=Response_train, 
##D  Matrix_covariates_train=Predictors_train, method="RKHS", rate_decay_kernel=5.0)
##D 
##D f_hat_target_Gaussian_KRR = Predict_kernel_Ridge_MM( Gaussian_KRR_model_train, 
##D  Matrix_covariates_target=Predictors_target )
##D 
##D 
##D #Graphics for RR-BLUP
##D 
##D dev.new(width=30, height=20)
##D par(mfrow=c(3,1))	
##D plot(f_hat_target_Linear_KRR, True_value_target)
##D plot(Linear_KRR_model_train$Gamma_hat, xlab="Feature (i.e. covariate) number", 
##D ylab="Feature effect (i.e. Gamma_hat)", main="BLUP of covariate effects based on training data")
##D hist(Linear_KRR_model_train$Gamma_hat, main="Distribution of BLUP of 
##D covariate effects based on training data" )
##D 
##D 
##D # Compare prediction based on linear (i.e. RR-BLUP) and Gaussian kernel
##D 
##D dev.new(width=30, height=20)
##D par(mfrow=c(1,2))
##D plot(f_hat_target_Linear_KRR, True_value_target)
##D plot(f_hat_target_Gaussian_KRR, True_value_target)
##D 
##D mean((f_hat_target_Linear_KRR - True_value_target)^2)
##D mean((f_hat_target_Gaussian_KRR - True_value_target)^2)
##D 
## End(Not run)




