library(KRMM)


### Name: Tune_kernel_Ridge_MM
### Title: Tune kernel ridge regression in the mixed model framework
### Aliases: Tune_kernel_Ridge_MM

### ** Examples
 

## Not run: 
##D 
##D library(KRMM)
##D 
##D ### SIMULATE DATA 
##D set.seed(123)
##D p=200
##D N=100
##D 
##D beta=rnorm(p, mean=0, sd=1.0)
##D X=matrix(runif(p*N, min=0, max=1), ncol=p, byrow=TRUE)  #X: covariates (i.e. predictors)
##D 
##D f=X%*%beta        #f: data generating process (i.e. DGP)
##D E=rnorm(N, mean=0, sd=0.5)
##D 
##D Y=f+E                                                  #Y: response data
##D 
##D hist(f)
##D hist(beta)
##D Nb_train=floor((2/3)*N)
##D 
##D ###======================================================================###
##D ###	CREATE TRAINING AND TARGET SETS FOR RESPONSE AND PREDICTOR VARIABLES ###
##D ###======================================================================###
##D 
##D Index_train=sample(1:N, size=Nb_train, replace=FALSE)
##D 
##D ### Covariates (i.e. predictors) for training and target sets
##D 
##D Predictors_train=X[Index_train, ]
##D Response_train=Y[Index_train]
##D 
##D Predictors_target=X[-Index_train, ]
##D True_value_target=f[-Index_train]    #True value (generated by DGP) we want to predict
##D 
##D ###=======================###
##D ### Tuned Gaussian Kernel ###
##D ###=======================###
##D 
##D Tuned_Gaussian_KRR_train = Tune_kernel_Ridge_MM( Y_train=Response_train, Matrix_covariates_train
##D =Predictors_train, method='RKHS', rate_decay_grid=seq(1,10,length.out=10), nb_folds=5, loss='mse' )
##D 
##D Tuned_Gaussian_KRR_model_train = Tuned_Gaussian_KRR_train$tuned_model
##D Tuned_Gaussian_KRR_train$optimal_h
##D Tuned_Gaussian_KRR_train$rate_decay_grid
##D Tuned_Gaussian_KRR_train$expected_loss_grid
##D 
##D dev.new()
##D plot(Tuned_Gaussian_KRR_train$rate_decay_grid, Tuned_Gaussian_KRR_train$expected_loss_grid,
##D  type="l", main="Tuning the rate of decay (for Gaussian kernel) with K-folds cross-validation")
##D 
##D ### Predict with tuned model
##D  
##D f_hat_target_tuned_Gaussian_KRR = Predict_kernel_Ridge_MM( Tuned_Gaussian_KRR_model_train, 
##D Matrix_covariates_target=Predictors_target )
##D 
##D mean((f_hat_target_tuned_Gaussian_KRR-True_value_target)^2)
##D cor(f_hat_target_tuned_Gaussian_KRR,True_value_target)
##D 
##D 
## End(Not run)





