library(dataMaid)


### Name: makeDataReport
### Title: Produce a data report
### Aliases: makeDataReport

### ** Examples

data(testData)
data(toyData)

check(toyData)

 ## Not run: 
##D DF <- data.frame(x = 1:15)
##D makeDataReport(DF)
## End(Not run)

## Not run: 
##D data(testData)
##D makeDataReport(testData)
## End(Not run)

# Overwrite any existing files generated by makeDataReport
## Not run: 
##D makeDataReport(testData, replace=TRUE)
## End(Not run)

# Change output format to Word/docx:
## Not run: 
##D makeDataReport(testData, replace=TRUE, output = "word")
## End(Not run)

# Only include problematic variables in the output document
## Not run: 
##D makeDataReport(testData, replace=TRUE, onlyProblematic=TRUE)
## End(Not run)

# Add user defined check-function to the checks performed on character variables:
# Here we add functionality to search for the string wally (ignoring case)
## Not run: 
##D wheresWally <- function(v, ...) {
##D      res <- grepl("wally", v, ignore.case=TRUE)
##D      problem <- any(res)
##D      message <- "Wally was found in these data"
##D      checkResult(list(problem = problem,
##D                       message = message,
##D                       problemValues = v[res]))
##D }
##D 
##D wheresWally <- checkFunction(wheresWally,
##D                              description = "Search for the string 'wally' ignoring case",
##D                              classes = c("character")
##D                              )
##D # Add the newly defined function to the list of checks used for characters.
##D makeDataReport(testData, 
##D       checks = setChecks(character = defaultCharacterChecks(with = "wheresWally")),
##D       replace=TRUE)
## End(Not run)

#Handle non-supported variable classes using treatXasY: treat raw as character and
#treat complex as numeric. We also add a list variable, but as lists are not 
#handled through treatXasY, this variable will be caught in the preChecks and skipped:
## Not run: 
##D toyData$rawVar <- as.raw(c(1:14, 1))
##D toyData$compVar <- c(1:14, 1) + 2i
##D toyData$listVar <- as.list(c(1:14, 1))
##D makeDataReport(toyData, replace  = TRUE, 
##D     treatXasY = list(raw = "character", complex = "numeric"))
## End(Not run)




