library(classyfire)


### Name: cfPredict
### Title: Predict the class of new data using an existing ensemble
### Aliases: cfPredict
### Keywords: classif multivariate models nonlinear

### ** Examples

## Not run: 
##D data(iris)
##D 
##D irisClass <- iris[,5]
##D irisData  <- iris[,-5]
##D 
##D # Construct a classification ensemble with 100 classifiers and 100 bootstrap 
##D # iterations during optimisation
##D 
##D ens <- cfBuild(irisData, irisClass, bootNum = 100, ensNum = 100, parallel = TRUE, 
##D                cpus = 4, type = "SOCK")
##D 
##D # Randomly generate test data to find out their classes using the generated ensemble
##D # 400 points are selected at random, which results in 100 samples (rows).
##D # Predict the classes of the data using the classifiers in the constructed ensemble
##D 
##D testMatr <- matrix(runif(400)*100, ncol=4)           
##D predRes  <- cfPredict(ens, testMatr)
##D 
##D # Get the attributes of the object predRes 
##D attributes(predRes)$names
##D 
##D # Get the predicted classes as generated by a majority vote between the classifiers
##D predRes$totalPred
##D 
##D # Get the individual classes as predicted by each classifier in the ensemble
##D predRes$indivPred
##D 
## End(Not run)



