library(unitizer)


### Name: all.equal.condition
### Title: Compare Conditions
### Aliases: all.equal.condition all.equal,condition,ANY-method
###   all.equal,conditionList,ANY-method all.equal.conditionList
###   all.equal.condition

### ** Examples

cond.1 <- simpleWarning('hello world')
cond.2 <- simpleError('hello world')
cond.3 <- simpleError('goodbye world')
all.equal(cond.1, cond.1)
all.equal(cond.1, cond.2)
all.equal(cond.2, cond.3)
## Normally you would never actually create a `conditionList` yourself; these
## are automatically generated by `unitizer` for review at the `unitizer`
## prompt
all.equal(
  conditionList(.items=list(cond.1, cond.2)),
  conditionList(.items=list(cond.1, cond.3))
)



