library(redland)


### Name: getBlankNodeId
### Title: Get the blank identifier that has been assigned for a specified
###   Node object
### Aliases: getBlankNodeId getBlankNodeId,Node-method

### ** Examples

world <- new("World")
# a blank node is created with a unique identifier generated by librdf
node <- new("Node", world, blank=NULL)
nodeId <- getBlankNodeId(node)



