---
title: "Data Builder"
output: html_notebook
---

WORKFLOW
0. build data on prl3
  0.1. reduce traces
  0.2. make_new_df \forall the packages
  0.3. rbindlist them all
1. get data from prl3 and do the notebook up to 2.
  

```{r}
source("../code/data_processing.R")
```

```{r}
# load the data
psp <- read_rds("../data/promise_big_final.RDS")

psp <- as.tibble(psp)

# get rid of empties
# they are due to packages having no data, this may get resolved as the prl3 run finishes
psp <- psp[!psp$pkg == "no_data",]

# first, turn specials, closures, and builtins to functions
psp <- transform_new_df_w_TS_map(psp, type_map_to_fun)

# do this otherwise there are lists
psp <- lists_to_chars_sig_df(psp)
```

```{r}
# make it T0
psp_L0 <- transform_new_df_w_TS_map(psp, type_map_T0_to_r, unparam = T)
psp_L0 <- lists_to_chars_sig_df(psp_L0)
```

WORKFLOW
2. write the partials out to csv for java
3. in java, call doIt (remember -L=L0 for L0, -L=L1 for L1) ALSO NOTE FILE NAMES

```{r}
# write it to file for Java processing
write_csv(psp_L0, "../data/L0.csv")
```

```{r}
# read in new one
psp_L0 <- read_csv("../data/L0_subtype.csv.gz")

# remove SUBTYPE rows
psp_L0 <- psp_L0[!psp_L0$pkg == "SUBTYPE",]
```

```{r}
# write L1 (which is just psp) to file for Java
write_csv(psp, "../data/L1.csv")

# go to terminal, gzip it for Java
```

```{r}
# read it back
psp <- read_csv("../data/L1_subtype.csv.gz")

# remove SUBTYPE rows
psp <- psp[!psp$pkg == "SUBTYPE",]
```

```{r}
# collapse
# make sure the right function is uncommented in Java

psp_L0_col <- read_csv("../data/L0_collapsed.csv.gz")
psp_col <- read_csv("../data/L1_collapsed.csv.gz")

```

```{r}
# arg counts
# again, Java
L0_arg_sig_c <- read_csv("../data/L0_arg_sig_counts.csv.gz")
L1_arg_sig_c <- read_csv("../data/L1_arg_sig_counts.csv.gz")

# sort
L0_arg_sig_c[order(-L0_arg_sig_c$count),] -> L0_arg_sig_c
L1_arg_sig_c[order(-L1_arg_sig_c$count),] -> L1_arg_sig_c

# rm []
# L0_arg_sig_c[1,"count"] <- 0
# L1_arg_sig_c[1,"count"] <- 0
L0_arg_sig_c <- L0_arg_sig_c[2:nrow(L0_arg_sig_c), ]
L1_arg_sig_c <- L1_arg_sig_c[2:nrow(L1_arg_sig_c), ]

# re sort
# L0_arg_sig_c[order(-L0_arg_sig_c$count),] -> L0_arg_sig_c
# L1_arg_sig_c[order(-L1_arg_sig_c$count),] -> L1_arg_sig_c

# percentages
L0_arg_sig_c$perc_tot <- round(L0_arg_sig_c$count / sum(L0_arg_sig_c$count) * 100, 2)
L1_arg_sig_c$perc_tot <- round(L1_arg_sig_c$count / sum(L1_arg_sig_c$count) * 100, 2)

# collapse the obvious signatures
L0_arg_sig_c <- new_df_count_collape_arg_sigs(L0_arg_sig_c, "L0")
L1_arg_sig_c <- new_df_count_collape_arg_sigs(L1_arg_sig_c, "L1")

# poly arg counts only
L0_poly_sig <- L0_arg_sig_c[L0_arg_sig_c$arg_sig %>% strsplit(split=",") %>% lapply(function(x) length(x) != 1) %>% unlist, ]
L1_poly_sig <- L1_arg_sig_c[L1_arg_sig_c$arg_sig %>% strsplit(split=",") %>% lapply(function(x) length(x) != 1) %>% unlist, ]

# display all args 
L0_arg_sig_c[1:10,] %>% ready_print_count_fun %>% xtable %>% print(include.rownames=F)
L1_arg_sig_c[1:10,] %>% ready_print_count_fun %>% xtable %>% print(include.rownames=F)

# display poly
L0_poly_sig[1:10,] %>% ready_print_count_fun %>% xtable %>% print(include.rownames=F)
L1_poly_sig[1:10,] %>% ready_print_count_fun %>% xtable %>% print(include.rownames=F)
```

```{r}
# all pckg (w/ dups)
pf_L0 <- psp_L0 %>% mutate(pkgfun = paste(pkg, fun, sep="::")) %>% select(pkgfun)
pf_L1 <- psp %>% mutate(pkgfun = paste(pkg, fun, sep="::")) %>% select(pkgfun)

# tot fun counts
pf_L0 %>% unique %>% nrow -> tot_L0_funs
pf_L1 %>% unique %>% nrow -> tot_L1_funs

# poly fun counts
pf_L0[duplicated(pf_L0),] %>% unique -> poly_L0_funs
pf_L1[duplicated(pf_L1),] %>% unique -> poly_L1_funs

poly_L0_funs_c <- poly_L0_funs %>% nrow
poly_L1_funs_c <- poly_L1_funs %>% nrow

# mono fun count (sanity check)
setdiff(pf_L0 %>% unique, poly_L0_funs) %>% nrow -> mono_L0_funs_c
setdiff(pf_L1 %>% unique, poly_L1_funs) %>% nrow -> mono_L1_funs_c

data.frame(`Signature Type`=c("Monomorphic", "Total Seen"), Count=paste0(c(mono_L0_funs_c/1000, tot_L0_funs/1000) %>% as.integer, "K"), Percentage=c(paste0(round(mono_L0_funs_c/tot_L0_funs * 100, 1), "%"), "---")) %>% xtable %>% print(include.rownames=F)

data.frame(`Signature Type`=c("Monomorphic", "Total Seen"), Count=paste0(c(mono_L1_funs_c/1000, tot_L1_funs/1000) %>% as.integer, "K"), Percentage=c(paste0(round(mono_L1_funs_c/tot_L1_funs * 100, 1), "%"), "---")) %>% xtable %>% print(include.rownames=F)

# actually want plots, next
```

```{r}
# Actually, want per fun plots
pf_L0 %>% mutate(num_sigs = 1) %>% group_by(pkgfun) %>% summarize(num_sigs=sum(num_sigs)) -> plot_L0
pf_L1 %>% mutate(num_sigs = 1) %>% group_by(pkgfun) %>% summarize(num_sigs=sum(num_sigs)) -> plot_L1

plot_L0 %>% arrange(num_sigs) %>% mutate(pkgfun_o = factor(pkgfun, pkgfun)) -> plot_L0_df
plot_L1 %>% arrange(num_sigs) %>% mutate(pkgfun_o = factor(pkgfun, pkgfun)) -> plot_L1_df

# if L0 has no data entry, get rid of it
if (plot_L0_df[plot_L0_df$pkgfun == "no_data::no_data",] %>% nrow == 1)
  plot_L0_df <- plot_L0_df[!plot_L0_df$pkgfun == "no_data::no_data",]

L0_perc_poly <- round(100 * nrow(plot_L0_df[plot_L0_df$num_sigs > 1, ] )/nrow(plot_L0_df), 1)
L1_perc_poly <- round(100 * nrow(plot_L1_df[plot_L1_df$num_sigs > 1, ] )/nrow(plot_L1_df), 1)

# maybe only plot those with more than 1 sig?
plot_L0_df %>%
  ggplot(aes(x=pkgfun_o, y=num_sigs, group=1)) +
  geom_line() + labs(title = "Number of Function Signatures per Function (L0)",
                                    x = "",
                                    y = "Number of L0 Signatures") + theme(axis.text.x = element_blank())

ggsave("../paper/plots/L0_by_fun.pdf",width=10,height=4)

# if want top 10
plot_L0_df %>% tail

plot_L1_df %>%
  ggplot(aes(x=pkgfun_o, y=num_sigs, group=1)) +
  geom_line() + labs(title = "Number of Function Signatures per Function (L1)",
                                    x = "",
                                    y = "Number of L1 Signatures") + theme(axis.text.x = element_blank())

ggsave("../paper/plots/L1_by_fun.pdf",width=10,height=4)

plot_L1_df %>% tail
```

```{r}
# arg poly count

# L0
data.frame(`Signature Type`=c("Monomorphic", "Total Seen"), Count=c(L0_arg_sig_c$count %>% sum - L0_poly_sig$count %>% sum, L0_arg_sig_c$count %>% sum), Percentage=c(paste0(round(100 * (1 - (L0_poly_sig$count %>% sum / L0_arg_sig_c$count %>% sum)), 1), "%"), "---")) %>% xtable %>% print(include.rownames=F)

# L1
data.frame(`Signature Type`=c("Monomorphic", "Total Seen"), Count=c(L1_arg_sig_c$count %>% sum - L1_poly_sig$count %>% sum, L1_arg_sig_c$count %>% sum), Percentage=c(paste0(round(100 * (1 - (L1_poly_sig$count %>% sum / L1_arg_sig_c$count %>% sum)), 1), "%"), "---")) %>% xtable %>% print(include.rownames=F)

```

```{r}
prim_scal <- c("sD", "sL", "sC", "sX", "sI", "sR")
# compute scalars 
L1_sc_c <- L1_arg_sig_c[unlist(lapply(L1_arg_sig_c$arg_sig, function(s) nchar(s) == 2 && substr(s, 1, 1) == "s")), ]
L1_sc_c <- L1_sc_c[L1_sc_c$arg_sig %in% prim_scal,]
num_scal <- sum(L1_sc_c$count)

percent_scalar_mono <- round( 100 * num_scal / sum(L1_arg_sig_c$count), 1)
```

```{r}
# L2 Time
psp_L2 <- read_csv("../data/L1_L2.csv.gz")
psp_L2 <- psp_L2[!psp_L2$pkg == "SUBTYPE",]
```

```{r}
# Plot it
pf_L2 <- psp_L2 %>% mutate(pkgfun = paste(pkg, fun, sep="::")) %>% select(pkgfun)

pf_L2 %>% mutate(num_sigs = 1) %>% group_by(pkgfun) %>% summarize(num_sigs=sum(num_sigs)) -> plot_L2

plot_L2 %>% arrange(num_sigs) %>% mutate(pkgfun_o = factor(pkgfun, pkgfun)) -> plot_L2_df

L2_perc_poly <- round(100 * nrow(plot_L2_df[plot_L2_df$num_sigs > 1, ] )/nrow(plot_L2_df), 1)

# gonna remove 2 outliers and talk about them separately
plot_L2_df <- plot_L2_df[1:(nrow(plot_L2_df)-2), ]

# THE L2 PLOT

plot_L2_df %>%
  ggplot(aes(x=pkgfun_o, y=num_sigs, group=1)) +
  geom_line() + labs(title = "Number of Function Signatures per Function (L2)",
                                    x = "",
                                    y = "Number of L2 Signatures") + theme(axis.text.x = element_blank())

ggsave("../paper/plots/L2_by_fun.pdf",width=10,height=4)

plot_L2_df %>% tail
```

```{r}
# L2 collapsed?
# what <- read_csv("../data/partial_L1_sanitized_class_collapsed.csv.gz")
what <- read_csv("../data/partial_L1_collapsed_L2_new.csv.gz")
```

```{r}
# ...
list_of_L2_sig_c <- read_csv("../data/L1_arg_sig_counts_L2.csv.gz")

list_of_L2_sig_c[order(-list_of_L2_sig_c$count),] -> list_of_L2_sig_c

list_of_L2_sig_c[1,"count"] <- 0

list_of_L2_sig_c[order(-list_of_L2_sig_c$count),] -> list_of_L2_sig_c

# remove last
list_of_L2_sig_c <- list_of_L2_sig_c[1:nrow(list_of_L2_sig_c)-1,]

list_of_L2_sig_c$perc_tot <- round(list_of_L2_sig_c$count / sum(list_of_L2_sig_c$count) * 100, 2)

list_of_L2_sig_c <- new_df_count_collape_arg_sigs_L2_actual(list_of_L2_sig_c)

list_of_L2_sig_c[1:10,] %>% ready_print_count_fun %>% xtable %>% print(include.rownames=F)

# poly arg counts only
L2_poly_sig <- list_of_L2_sig_c[list_of_L2_sig_c$arg_sig %>% strsplit(split="/") %>% lapply(function(x) length(x) != 3) %>% unlist, ]

# remove error 
L2_poly_sig[1, "count"] <- 0
L2_poly_sig[1, "perc_tot"] <- 0

# display poly
L2_poly_sig[2:11,] %>% ready_print_count_fun %>% xtable %>% print(include.rownames=F)

# Arg Poly Count L2
data.frame(`Signature Type`=c("Monomorphic", "Total Seen"), Count=c(list_of_L2_sig_c$count %>% sum - L2_poly_sig$count %>% sum, list_of_L2_sig_c$count %>% sum), Percentage=c(paste0(round(100 * (1 - (L2_poly_sig$count %>% sum / list_of_L2_sig_c$count %>% sum)), 2), "%"), "---")) %>% xtable %>% print(include.rownames=F)
```

```{r}
# packages with the most polymorphism
# which TS to use for this?

num_funs_by_pkg <- psp_L0 %>% group_by(pkg, fun) %>% select(pkg, fun) %>% distinct(fun) %>% mutate(count=1) %>% group_by(pkg) %>% summarize(count=sum(count))

num_sigs_by_pkg <- psp_L0 %>% mutate(sig_count = 1) %>% group_by(pkg) %>% summarize(sig_count=sum(sig_count))

poly_count_normalized <- inner_join(num_funs_by_pkg, num_sigs_by_pkg, by="pkg") %>% mutate(poly_norm=sig_count/count)

poly_count_normalized %>% arrange(-poly_norm) %>% slice(1:10) %>% xtable %>% print(include.rownames=F)

# print

```

Old stuff.
```{r}
# arg sig counts?
# L2_arg_sig_c <- read_csv("../data/partial_L1_sanitized_class_arg_sig_counts_L2.csv.gz")
# 
# # sort
# L2_arg_sig_c[order(-L2_arg_sig_c$count),] -> L2_arg_sig_c
# 
# # rm []/[]/[]
# L2_arg_sig_c[1,"count"] <- 0
# 
# # resort
# L2_arg_sig_c[order(-L2_arg_sig_c$count),] -> L2_arg_sig_c
# 
# # %
# L2_arg_sig_c$perc_tot <- round(L2_arg_sig_c$count / sum(L2_arg_sig_c$count) * 100, 1)
# 
# # collapse obvious subtypes
# # gets rid of stuff in the first box
# L2_arg_sig_c <- new_df_count_collape_arg_sigs_L2(L2_arg_sig_c)
# 
# # what counts do we want?
# # split typeclassattr into type class attr
# L2_split <- split_L2_df(L2_arg_sig_c)
# 
# # group class
# L2_split$Class <- L2_split$Class %>% as.character %>% strsplit(split=", ") %>% sapply(function(x) sapply(x, function(y) paste0("[", paste(y, collapse=", "), "]"))) %>% sapply(function(s) paste(s, collapse=", "))
# 
# # display top
# L2_split[1:10,] %>% ready_print_count_fun_L2 %>% xtable %>% print(include.rownames=F)
# L2_split %>% filter(Class != "") %>% slice(1:10) %>% as.data.frame %>% ready_print_count_fun_L2 %>% xtable %>% print(include.rownames=F)
# 
# L2_poly_ind <- sapply(as.character(L2_split$Type), function(s) length(unlist(strsplit(s, split=", "))) > 1) |
#                sapply(as.character(L2_split$Class), function(s) length(unlist(strsplit(s, split=", "))) > 1) |
#                sapply(as.character(L2_split$Attr), function(s) length(unlist(strsplit(s, split=", "))) > 1)
# L2_poly_sig <- L2_split[L2_poly_ind, ]
# 
# # display
# head(L2_poly_sig, 10) %>% ready_print_count_fun_L2 %>% xtable %>% print(include.rownames=F)
```