---
title: "R Notebook"
output: html_notebook
---

This is the notebook for the NEW results section.

Step 0: Administrivia.
```{r}
source("../code/data_processing.R") # get the functions we need

library(xtable)
```

Step 1: Load Data
```{r}
los <- list.files("../data/full_sigs", full.names=TRUE)
names <- list.files("../data/full_sigs")
names(los) <- substr(names, 1, nchar(names)-4)
los <- lapply(los, readRDS)
los <- remove_empties(los)
```

Step 2: Get data ready for L1.
So: Translate the type system to R.
```{r}
los <- change_type_systems_lopkg(los, type_map_T0_to_r, unparam=T)
```

Step 2.1: Counts.
```{r}
L1_c_basic_df <- build_arg_count_df_from_lopkgs(los)

L1_c_f_basic_df <- build_fun_count_df_from_lopkgs(los)
```

```{r}
xtable(L1_c_basic_df) %>% print(include.rownames=F)
xtable(L1_c_f_basic_df) %>% print(include.rownames=F)
```

Step 2.2: Top.
```{r}
L1_poly_type_args <- reduce_extracted_lopkgs_to_one(apply_extract_to_lopkg(los, extract_poly_type_args))
L1_poly_type_args <- L1_poly_type_args[order(-L1_poly_type_args$count),] # sort by count
L1_poly_type_args$perc <- round(L1_poly_type_args$count/sum(L1_poly_type_args$count) * 100, 2)
```

Step 2.3: Print top 10.
```{r}
format_df_for_print(L1_poly_type_args[1:10,]) %>%
xtable %>% print(include.rownames=F)
```

Step 3: Translate to L2.
```{r}
# We need to reload b/c we lost information in L1.
los <- list.files("../data/full_sigs", full.names=TRUE)
names <- list.files("../data/full_sigs")
names(los) <- substr(names, 1, nchar(names)-4)
los <- lapply(los, readRDS)
los <- remove_empties(los)
# annoying strange error that I should fix pops up

# There's at least one transformation that we're always gonna want to apply, namly the vector/scalar
# collapse where both are present in a signature.
los <- lapply(los, function(lofuns) {lapply(lofuns, combine_scalar_vector_where_appropriate)})
# Figure out which ones are matrices. Remove if the analysis picks this up (and we rerun).
los <- lapply(los, function(lofun) lapply(lofun, distinguish_matrices_df))
# remove "errors"
los <- lapply(los, function(lofun) lapply(lofun, remove_err_df))
```

Step 3.1: Counts.
```{r}
# argument counts
c_basic_df <- build_arg_count_df_from_lopkgs(los)

# function counts
c_f_basic_df <- build_fun_count_df_from_lopkgs(los)

xtable(c_f_basic_df) %>% print(include.rownames=F)
xtable(c_basic_df) %>% print(include.rownames=F)

```

Step 3.2: Top.
```{r}
poly_type_args <- reduce_extracted_lopkgs_to_one(apply_extract_to_lopkg(los, extract_poly_type_args))
poly_type_args <- poly_type_args[order(-poly_type_args$count),] # sort by count
poly_type_args$perc <- round(poly_type_args$count/sum(poly_type_args$count) * 100, 2)
```

Step 3.3: Print top 10.
```{r}
format_df_for_print(poly_type_args[1:10,]) -> put_me
put_me
xtable(put_me) %>% print(include.rownames=F)
```


