library(frailtypack)


### Name: jointSurroPenal
### Title: Fit the one-step Joint surrogate model for the evaluation of a
###   canditate surrogate endpoint
### Aliases: jointSurroPenal

### ** Examples


# Generation of data to use 
data.sim <- jointSurrSimul(n.obs=600, n.trial = 30,cens.adm=549.24, 
         alpha = 1.5, theta = 3.5, gamma = 2.5, zeta = 1, sigma.s = 0.7, 
         sigma.t = 0.7, rsqrt = 0.8, betas = -1.25, betat = -1.25, 
         full.data = 0, random.generator = 1, seed = 0, nb.reject.data = 0)

## Not run: 
##D #Surrogacy evaluation based on ganerated data with a combination of Monte Carlo 
##D and classical Gaussian Hermite integration.*
##D # (Computation takes around 5 minutes)
##D 
##D joint.surro.sim.MCGH <- jointSurroPenal(data = data.sim, int.method = 2, 
##D                    nb.mc = 300, nb.gh = 20)
##D                    
##D #Surrogacy evaluation based on ganerated data with a combination of Monte Carlo 
##D # and Pseudo-adaptive Gaussian Hermite integration.
##D # (Computation takes around 4 minutes)
##D 
##D joint.surro.sim.MCPGH <- jointSurroPenal(data = data.sim, int.method = 2, 
##D                    nb.mc = 300, nb.gh = 20, adaptatif = 1)
##D                    
##D # Results
##D summary(joint.surro.sim.MCGH)
##D summary(joint.surro.sim.PMCGH)
##D 
##D # Data from the advanced ovarian cancer randomized clinical trials.
##D # Joint surrogate model with \eqn{\zeta} fixed to \code{1}, 8 nodes spline 
##D # and the rescaled survival time. 
##D 
##D data(dataOvarian)
##D # (Computation takes around 13 minutes)
##D  
##D joint.surro.ovar <- jointSurroPenal(data = dataOvarian, n.knots = 8, 
##D                 init.kappa = c(2000,1000), indice.alpha = 0, nb.mc = 200, 
##D                 scale = 1/365)
##D # results
##D summary(joint.surro.ovar)
##D 
##D # data from the adjuvant chemotherapy and resectable gastric cancer 
##D   meta-analyses :
##D # Joint surrogate model with initial values for the parameters and the 
##D # smoothing parameters, and sample for the Monte-Carlo integration
##D # generated by the subroutine \code{uniran}.
##D # (Computation takes around 14 minutes)
##D 
##D data(gastadj)
##D joint.surro.gast <- jointSurroPenal(data = gastadj, nb.mc = 100, nb.gh = 20, 
##D                 indice.zeta = 0, indice.alpha = 0, n.knots = 10, 
##D                 random.generator = 2, init.kappa = c(367700100,10025184521))
##D 
##D # results
##D summary(joint.surro.gast)
##D 
## End(Not run)




