library(SpecsVerification)


### Name: DressCrps
### Title: Calculate the Continuous Ranked Probability Score (CRPS) for a
###   mixture of Normal distributions, for example generated by ensemble
###   dressing
### Aliases: DressCrps

### ** Examples

data(eurotempforecast)
dressed.ens <- DressEnsemble(ens)
mean(DressCrps(dressed.ens, obs))



