library(SpecsVerification)


### Name: DressIgn
### Title: Calculate the Logarithmic (Ignorance) Score for a mixture of
###   Normal distributions, for example generated by ensemble dressing
### Aliases: DressIgn

### ** Examples

data(eurotempforecast)
d.ens <- DressEnsemble(ens)
DressIgn(d.ens, obs)



