library(fasjem)


### Name: plot.fasjem
### Title: Plotting functions for displaying the list of multiple graphs
###   generated by the fasjem algorithm
### Aliases: plot.fasjem
### Keywords: fasjem

### ** Examples

  ## Not run: 
##D     data(exampleData)
##D     results = fasjem(X = exampleData, method = "fasjem-g", 0.1, 0.1, 0.1, 0.05, 10)
##D     plot.fasjem(results)
##D     plot.fasjem(results, type="share")
##D     plot.fasjem(results, type="sub", subID=1)
##D     plot.fasjem(results, type="neighbor", index=50)
##D   
## End(Not run)



