library(dtwclust)


### Name: tsclusters-methods
### Title: Methods for 'TSClusters'
### Aliases: tsclusters-methods TSClusters-methods
###   initialize,TSClusters-method initialize,TSClusters
###   show,TSClusters-method show,TSClusters update.TSClusters
###   update,TSClusters-method update,TSClusters predict.TSClusters
###   predict,TSClusters-method predict,TSClusters plot.TSClusters
###   plot,TSClusters,missing-method plot,TSClusters,missing

### ** Examples


data(uciCT)

# Assuming this was generated by some clustering procedure
centroids <- CharTraj[seq(1L, 100L, 5L)]
cluster <- unclass(CharTrajLabels)

pc_obj <- new("PartitionalTSClusters",
              type = "partitional", datalist = CharTraj,
              centroids = centroids, cluster = cluster,
              distance = "sbd", centroid = "dba",
              control = partitional_control(),
              args = tsclust_args(cent = list(window.size = 8L, norm = "L2")))

fc_obj <- new("FuzzyTSClusters",
              type = "fuzzy", datalist = CharTraj,
              centroids = centroids, cluster = cluster,
              distance = "sbd", centroid = "fcm",
              control = fuzzy_control())

show(fc_obj)


## Not run: 
##D plot(pc_obj, type = "c", linetype = "solid",
##D      labs.arg = list(title = "Clusters' centroids"))
##D 
##D set.seed(15L)
##D plot(pc_obj, labels = list(nudge_x = -5, nudge_y = 0.2),
##D      clus = c(1L,4L))
## End(Not run)




