library(LocalControl)


### Name: LocalControlCompetingRisksConfidence
### Title: Calculate confidence intervals around the cumulative incidence
###   functions (CIFs) generated by LocalControl when outcomeType =
###   "survival".
### Aliases: LocalControlCompetingRisksConfidence

### ** Examples

 data(cardSim)
 results = LocalControl(data = cardSim,
                        outcomeType = "survival",
                        outcomeColName = "status",
                        timeColName = "time",
                        treatmentColName = "drug",
                        treatmentCode = 1,
                        clusterVars = c("age", "bmi"))

 conf = LocalControlCompetingRisksConfidence(results)




