library(seqMeta)


### Name: seqMetaExample
### Title: Example data for illustrating seqMeta
### Aliases: seqMetaExample Z1 Z2 pheno1 pheno2 kins
### Keywords: datasets

### ** Examples

#Data generated by
## Not run: 
##D set.seed(20)
##D n <- 600 #observations per cohort
##D d <- 2000 #SNPs
##D k <- 100 #genes
##D 
##D ##### First cohort of unrelated individuals:
##D Z1 <- replicate(d,rbinom(n,2,rbeta((n),3,200)))
##D 
##D ## assign SNP id's to the columns 
##D colnames(Z1) <- sample(d+50,d) + 1e6
##D 
##D pheno1 <-  data.frame("y" = rnorm(n), "sex"=rep(1:2,(n/2)), "bmi"=rnorm(n,25,2),
##D 	"ybin" = rbinom(n,1,.5), "time"=rpois(n,5), "status"=rbinom(n,1,.9))
##D 
##D genes <- paste0("gene",1:k)
##D SNPInfo <-data.frame("Name"=as.character(1:(d+50) + 1e6), 
##D "gene"=sort(sample(genes,d+50,replace=T)), stringsAsFactors=FALSE)
##D #SNPInfo <- data.frame("Name" =1:(d+50) + 1e6, "gene" = sort(sample(genes,d+50,replace=T)))
##D 
##D #####Second cohort of family data:
##D # 150 families of size 4
##D require(kinship2)
##D fullped<-data.frame(famid=rep(1:(n/4),each=4),id=10001:(10000+n),fa=rep(0,n),mo=rep(0,n))
##D fullped$fa[(1:(n/4))*4-1]<-fullped$fa[(1:(n/4))*4]<-(1:(n/4))*4+9997
##D fullped$mo[(1:(n/4))*4-1]<-fullped$mo[(1:(n/4))*4]<-(1:(n/4))*4+9998
##D kins = makekinship(fullped$famid, fullped$id, fullped$fa, fullped$mo)
##D 
##D ## generate a phenotype with 20% `heritability': 
##D pheno2<-data.frame("id"=10001:(10000+n),"y"=t(rnorm(n)%*%chol(0.2*2*as.matrix(kins) + 
##D 	0.8*diag(n))),"sex"=rep(1:2,(n/2)),"bmi"=rnorm(n,25,2))
##D 
##D Z2 <- replicate(d,rbinom(n,2,rbeta((n/4),3,200)[fullped$famid]))
##D colnames(Z2) <- sample(d+50,d) + 1e6
## End(Not run)



