library(mudfold)


### Name: mudfold
### Title: MUDFOLD: Van Schuur's nonparametric IRT model for dichotomous
###   responses that have been generated by an unfolding process.
### Aliases: mudfold

### ** Examples

## Not run: 
##D #####################################
##D #### MUDFOLD method on real data ####
##D #####################################
##D 
##D 
##D 
##D ###########################################################################
##D ###### MUDFOLD method on ANDRICH data (see Post and Snijders pp.147) ######
##D ###########################################################################
##D data(ANDRICH)
##D ## fit MUDFOLD on ANDRICH data ##
##D fit_andr <- mudfold(ANDRICH)
##D 
##D ## generic functions for the S3 class .mdf object fit ##
##D ## print.mdf
##D print(fit_andr)
##D ## summary.mdf
##D summary(fit_andr, diagnostics=TRUE)
##D ## plot.mdf
##D plot(fit_andr)
##D 
##D 
##D ## fit MUDFOLD on ANDRICH data with bootsrap ##
##D fit_andr_boot <- mudfold(ANDRICH, nboot=100)
##D 
##D ## generic functions for the S3 class .mdf object fit ##
##D ## print.mdf
##D print(fit_andr_boot)
##D ## summary.mdf
##D summary(fit_andr_boot, boot=TRUE, diagnostics=FALSE)
##D ## plot.mdf
##D plot(fit_andr_boot)
##D 
##D ############################################
##D ###### MUDFOLD method on EURPAR2 data ######
##D ############################################
##D data("EURPAR2")
##D 
##D ## fit MUDFOLD on EURPAR2 data ##
##D fit_eurp <- mudfold(EURPAR2)
##D 
##D ## print
##D print(fit_eurp,Diagnostics = TRUE)
##D 
##D ## summary
##D summary(fit_eurp)
##D 
##D ## plot
##D plot(fit_eurp)
##D 
##D ###########################################
##D ###### MUDFOLD method on Plato7 data ######
##D ###########################################
##D 
##D data("Plato7")
##D 
##D ## transform to binary data
##D ## using as threshold the mean
##D ## per row of Plato7
##D 
##D dat_plato <- pick(Plato7)
##D 
##D ## fit MUDFOLD on Plato7 data ##
##D fit_plato <- mudfold(dat_plato, nboot=1000)
##D 
##D ## print
##D print(fit_plato)
##D 
##D ## summary
##D summary(fit_plato, boot=TRUE)
##D 
##D ## plot
##D plot(fit_plato, plot.type="scale")
##D plot(fit_plato, plot.type="IRF")
##D plot(fit_plato, plot.type="persons")
##D 
##D 
##D ##########################################
##D #### MUDFOLD method on simulated data ####
##D ##########################################
##D 
##D ### Data with the responses of
##D ### n=3000 on p=20 items
##D 
##D simulation1 <- mudfoldsim(N=20, n=3000, gamma1=2, gamma2=-10, zeros=FALSE,seed = 1)
##D dat_sim1 <- simulation1$dat
##D 
##D ## fit MUDFOLD on simulated data ##
##D fit.sim1 <- mudfold(dat_sim1)
##D 
##D # print
##D fit.sim1
##D 
##D # summary
##D summary(fit.sim1)
##D 
##D # plot
##D plot(fit.sim1)
##D 
##D ### Data with the responses of
##D ### n=3000 on N=26 items
##D 
##D simulation2 <- mudfoldsim(N=26, n=3000, gamma1=2, gamma2=-10, zeros=FALSE,seed = 1)
##D dat_sim2 <- simulation2$dat
##D 
##D ## fit MUDFOLD on simulated data ##
##D fit.sim2 <- mudfold(dat_sim2)
##D 
##D # print
##D fit.sim2
##D 
##D # summary
##D summary(fit.sim2)
##D 
##D # plot
##D plot(fit.sim2, plot.type="scale")
##D plot(fit.sim2, plot.type="IRF")
##D plot(fit.sim2, plot.type="persons")
##D 
## End(Not run)



