library(embryogrowth)


### Name: logLik.tsd
### Title: Return Log Likelihood of a fit generated by tsd
### Aliases: logLik.tsd

### ** Examples

## Not run: 
##D library(embryogrowth)
##D m <- c(10, 14, 7, 4, 3, 0, 0)
##D f <- c(0, 1, 2, 4, 15, 10, 13)
##D t <- c(25, 26, 27, 28, 29, 30, 31)
##D result <- tsd(males=m, females=f, temperatures=t)
##D logLik(result)
##D AIC(result)
## End(Not run)



