library(embryogrowth)


### Name: logLik.NestsResult
### Title: Return Log Likelihood of a fit generated by searchR
### Aliases: logLik.NestsResult

### ** Examples

## Not run: 
##D library(embryogrowth)
##D data(resultNest_4p_SSM4p)
##D logLik(resultNest_4p_SSM4p)
##D AIC(resultNest_4p_SSM4p)
## End(Not run)



