library(embryogrowth)


### Name: logLik.STRN
### Title: Return Log Likelihood of a fit generated by STRN
### Aliases: logLik.STRN

### ** Examples

## Not run: 
##D library(embryogrowth)
##D data(resultNest_4p_SSM4p)
##D logLik(resultNest_4p_SSM4p)
##D AIC(resultNest_4p_SSM4p)
## End(Not run)



