library(CPBayes)


### Name: post_summaries
### Title: Post summary of the MCMC data generated by the uncorrelated or
###   correlated version of CPBayes.
### Aliases: post_summaries

### ** Examples

data(ExampleDataUncor)
BetaHat <- ExampleDataUncor$BetaHat
BetaHat
SE <- ExampleDataUncor$SE
SE
traitNames <- paste("Disease", 1:10, sep = "")
SNP1 <- "rs1234"
result <- cpbayes_uncor(BetaHat, SE, Phenotypes = traitNames, Variant = SNP1)
PleioSumm <- post_summaries(result, level = 0.05)
str(PleioSumm)




