library(rEMM)


### Name: EMMsim
### Title: Synthetic Data to Demonstrate EMMs
### Aliases: EMMsim EMMsim_train EMMsim_test EMMsim_sequence_train
###   EMMsim_sequence_test
### Keywords: datasets

### ** Examples

## the data was generated by
## Not run: 
##D set.seed(1234)
##D 
##D ## simulated data
##D mu <- cbind(
##D     x = c(0, 0.2,1,0.9),
##D     y = c(0, 0.7,1,0.2)
##D )
##D 
##D sd_rho <- cbind(
##D     x = c(0.2, 0.15, 0.05, 0.02),
##D     y = c(0.1, 0.04, 0.03, 0.05),
##D     rho = c(0, 0.7, 0.3, -0.4)
##D )
##D 
##D Sigma <- lapply(1:nrow(sd_rho), FUN = function(i) rbind(
##D         c(sd_rho[i,"x"]^2, sd_rho[i,"rho"]*sd_rho[i,"x"]*sd_rho[i,"y"]),
##D         c(sd_rho[i,"rho"]*sd_rho[i,"x"]*sd_rho[i,"y"], sd_rho[i,"y"]^2)))
##D 
##D 
##D sequence <- c(1,2,1,3,4)
##D 
##D EMMsim_sequence_train <- rep(sequence, 40)
##D EMMsim_sequence_test <- rep(sequence, 5)
##D 
##D library("MASS")
##D EMMsim_train <- t(sapply(EMMsim_sequence_train, FUN = function(i)
##D         mvrnorm(1, mu=mu[i,], Sigma=Sigma[[i]])))
##D EMMsim_test <- t(sapply(rep(EMMsim_sequence_test), FUN = function(i)
##D         mvrnorm(1, mu=mu[i,], Sigma=Sigma[[i]])))
## End(Not run)



