library(saasCNV)


### Name: GC.adjust
### Title: GC Content Adjustment
### Aliases: GC.adjust
### Keywords: CNV GC content

### ** Examples

## CNV data generated by cnv.data
data(seq.data)
head(seq.data)

## Not run: 
##D ## an example GC content file
##D url <- "https://zhangz05.u.hpc.mssm.edu/saasCNV/data/GC_1kb_hg19.txt.gz"
##D tryCatch({download.file(url=url, destfile="GC_1kb_hg19.txt.gz")
##D          }, error = function(e) {
##D           download.file(url=url, destfile="GC_1kb_hg19.txt.gz", method="curl")
##D          })
##D ## If download.file fails to download the data, please manually download it from the url.
##D 
##D gc <- read.delim(file = "GC_1kb_hg19.txt.gz", as.is=TRUE)
##D head(gc)
##D 
##D ## GC content adjustment
##D seq.data <- GC.adjust(data = seq.data, gc = gc, maxNumDataPoints = 10000)
##D head(seq.data)
## End(Not run)




