library(HHG)


### Name: hhg.univariate.ks.combined.test
### Title: Distribution-free K-sample tests
### Aliases: hhg.univariate.ks.combined.test

### ** Examples

## Not run: 
##D #Two groups, each from a different normal mixture:
##D N0=30
##D N1=30
##D X = c(c(rnorm(N0/2,-2,0.7),rnorm(N0/2,2,0.7)),c(rnorm(N1/2,-1.5,0.5),rnorm(N1/2,1.5,0.5)))
##D Y = (c(rep(0,N0),rep(1,N1)))
##D plot(Y,X)
##D 
##D #I) Perform MinP & Fisher Tests - without existing null tables.
##D #Null tables are generated by the test function.
##D 
##D results = hhg.univariate.ks.combined.test(X,Y,nr.perm = 100)
##D results
##D 
##D 
##D #The null table can then be accessed.
##D generated.null.table = results$generated_null_table
##D 
##D 
##D #II)Perform MinP & Fisher Tests - with existing null tables. 
##D 
##D #null table for aggregation by summation: 
##D sum.nulltable = hhg.univariate.ks.nulltable(c(N0,N1), nr.replicates=1000) 
##D 
##D MinP.Sm.existing.null.table = hhg.univariate.ks.combined.test(X,Y,
##D NullTable = sum.nulltable)
##D 
##D #Results
##D MinP.Sm.existing.null.table
##D 
##D # combined test can also be performed by using the test statistic.
##D Sm.statistic = hhg.univariate.ks.stat(X,Y)
##D MinP.using.statistic = hhg.univariate.ks.combined.test(Sm.statistic,
##D NullTable = sum.nulltable)
##D # same result as above
##D MinP.using.statistic$MinP.pvalue
##D 
##D #null table for aggregation by maximization: 
##D max.nulltable = hhg.univariate.ks.nulltable(c(N0,N1), aggregation.type = 'max', 
##D   score.type='LikelihoodRatio', mmin = 2, mmax = 10, nr.replicates = 100)
##D 
##D #combined test using both "MinP" and "Fisher":
##D MinPFisher.Mm.result = hhg.univariate.ks.combined.test(X,Y,NullTable =  max.nulltable ,
##D   combining.type = 'Both')
##D MinPFisher.Mm.result
##D 
##D 
##D #III) Perform MinP & Fisher Tests for extremly large n
##D 
##D #Two groups, each from a different normal mixture, total sample size is 10^4:
##D X_Large = c(c(rnorm(2500,-2,0.7),rnorm(2500,2,0.7)),
##D c(rnorm(2500,-1.5,0.5),rnorm(2500,1.5,0.5)))
##D Y_Large = (c(rep(0,5000),rep(1,5000)))
##D plot(Y_Large,X_Large)
##D 
##D 
##D N0_large = 5000
##D N1_large = 5000
##D 
##D Sm.EQP.null.table = hhg.univariate.ks.nulltable(c(N0_large,N1_large), nr.replicates=200,
##D variant = 'KSample-Equipartition', mmax = 30)
##D Mm.EQP.null.table = hhg.univariate.ks.nulltable(c(N0_large,N1_large), nr.replicates=200,
##D aggregation.type='max', variant = 'KSample-Equipartition', mmax = 30)
##D 
##D MinPFisher.Sm.EQP.result = hhg.univariate.ks.combined.test(X_Large, Y_Large,
##D NullTable =  Sm.EQP.null.table ,
##D   combining.type = 'Both')
##D MinPFisher.Sm.EQP.result
##D 
##D MinPFisher.Mm.EQP.result = hhg.univariate.ks.combined.test(X_Large, Y_Large,
##D NullTable =  Mm.EQP.null.table ,
##D   combining.type = 'Both')
##D MinPFisher.Mm.EQP.result
##D 
##D 
##D 
## End(Not run)





