library(HHG)


### Name: hhg.univariate.ind.combined.test
### Title: Distribution-free test of independence
### Aliases: hhg.univariate.ind.combined.test

### ** Examples


## Not run: 
##D 
##D N = 35
##D data = hhg.example.datagen(N, 'Parabola')
##D X = data[1,]
##D Y = data[2,]
##D plot(X,Y)
##D 
##D #I) Perform MinP & Fisher Tests - without existing null tables.
##D #Null tables are generated by the test function.
##D #using partitions sizes up to 5
##D results = hhg.univariate.ind.combined.test(X,Y,nr.perm = 100,mmax=5)
##D results
##D 
##D 
##D #The null table can then be accessed.
##D generated.null.table = results$generated_null_table
##D 
##D 
##D #II) Perform MinP & Fisher Tests - with existing null tables. 
##D 
##D #create null table for aggregation by summation (on ADP), with partitions sizes up to 5: 
##D ADP.null = hhg.univariate.ind.nulltable(N,mmax=5)
##D 
##D #create a null table, using aggregation by summation over DDP partitions,
##D #with partitions sizes up to 5, over Pearson scores,
##D #with 1000 bootstrap repetitions.
##D DDP.null = hhg.univariate.ind.nulltable(N,mmax = 5,variant = 'DDP',
##D score.type = 'Pearson', nr.replicates = 1000)
##D 
##D MinP.ADP.existing.null.table = hhg.univariate.ind.combined.test(X,Y, NullTable = ADP.null)
##D #Results 
##D MinP.ADP.existing.null.table
##D 
##D #using the other null table (DDP variant, with pearson scores):
##D MinP.DDP.existing.null.table = hhg.univariate.ind.combined.test(X,Y, NullTable = DDP.null)
##D 
##D MinP.DDP.existing.null.table
##D 
##D # combined test can also be performed by using the test statistic.
##D ADP.statistic = hhg.univariate.ind.stat(X,Y,mmax=5)
##D MinP.using.statistic.result = hhg.univariate.ind.combined.test(ADP.statistic,
##D NullTable = ADP.null)
##D # same result as above (as MinP.ADP.result.using.existing.null.table$MinP.pvalue)
##D MinP.using.statistic.result$MinP.pvalue
##D 
##D #III) Perform MinP & Fisher Tests - using the efficient variants for large N. 
##D 
##D N_Large = 1000
##D data_Large = hhg.example.datagen(N_Large, 'W')
##D X_Large = data_Large[1,]
##D Y_Large = data_Large[2,]
##D plot(X_Large,Y_Large)
##D 
##D NullTable_for_N_Large_MXM_tables = hhg.univariate.ind.nulltable(N_Large,
##D variant = 'ADP-EQP',nr.atoms = 30,nr.replicates=200)
##D NullTable_for_N_Large_MXL_tables = hhg.univariate.ind.nulltable(N_Large,
##D variant = 'ADP-EQP-ML',nr.atoms = 30,nr.replicates=200)
##D 
##D ADP_EQP_Result = hhg.univariate.ind.combined.test(X_Large,Y_Large,
##D NullTable_for_N_Large_MXM_tables)
##D ADP_EQP_ML_Result = hhg.univariate.ind.combined.test(X_Large,Y_Large,
##D NullTable_for_N_Large_MXL_tables)
##D 
##D ADP_EQP_Result
##D ADP_EQP_ML_Result
##D 
## End(Not run)





