library(multitaper)


### Name: percivalAR4
### Title: Auto Regressive Series generated by Don Percival at Applied
###   Physics Laboratory
### Aliases: percivalAR4
### Keywords: datasets

### ** Examples

## get the Percival realization of the series saved as data.
data(percivalAR4)
## generate another realization of this series using the same AR(4)
## coefficients.
ar4Coef <- c(2.7607, -3.8106, 2.6535, -0.9238)
ar4.ts <- arima.sim(list(order = c(4, 0, 0), ar=ar4Coef), n=1024)



