library(galgo)


### Name: newRandomCollection.World
### Title: Creates a list of cloned object with its internal values
###   generated by random
### Aliases: newRandomCollection.World World.newRandomCollection
###   newRandomCollection.World newRandomCollection,World-method
###   newRandomCollection
### Keywords: methods internal methods

### ** Examples

   cr <- Chromosome(genes=newCollection(Gene(shape1=1, shape2=100),5))
   cr
 
   ni <- Niche(chromosomes = newRandomCollection(cr, 2))
   ni

   wo <- World(niches = newRandomCollection(ni, 2))
   wo
 


