library(galgo)


### Name: newRandomCollection.Chromosome
### Title: Creates a list of cloned chromosomes object with its internal
###   values generated by random
### Aliases: newRandomCollection.Chromosome Chromosome.newRandomCollection
###   newRandomCollection.Chromosome newRandomCollection,Chromosome-method
### Keywords: methods internal methods

### ** Examples

   cr <- Chromosome(genes=newCollection(Gene(shape1=1, shape2=100),5))
   cr
 
   # creation and random generation at the same time
   ni <- Niche(chromosomes = newRandomCollection(cr, 2))
   ni
 


