library(galgo)


### Name: newRandomCollection.Niche
### Title: Creates a list of cloned niches with its internal values
###   generated by random
### Aliases: newRandomCollection.Niche Niche.newRandomCollection
###   newRandomCollection.Niche newRandomCollection,Niche-method
### Keywords: methods internal methods

### ** Examples

   cr <- Chromosome(genes=newCollection(Gene(shape1=1, shape2=100),5))
   cr
 
   ni <- Niche(chromosomes = newRandomCollection(cr, 2))
   ni

   wo <- World(niches = newRandomCollection(ni, 2))
   wo
 


