library(GGIR)


### Name: g.analyse
### Title: function to analsyse meta-data generated by g.getmeta and
###   g.impute
### Aliases: g.analyse

### ** Examples

data(data.getmeta)
data(data.inspectfile)
data(data.calibrate)
## Not run: 
##D   #inspect file:
##D   I = g.inspectfile(datafile)
##D   
##D   #autocalibration:
##D   C = g.calibrate(datafile) 
##D   
##D   #get meta-data:
##D   M = g.getmeta(datafile, desiredtz = "Europe/London", 
##D   windowsizes = c(5, 900, 3600),
##D   daylimit = FALSE, offset = c(0, 0, 0), 
##D   scale = c(1, 1, 1), tempoffset = c(0, 0, 0))
## End(Not run)


#impute meta-data:
IMP = g.impute(M = data.getmeta, I = data.inspectfile)

#analyse and produce summary:
A = g.analyse(I = data.inspectfile, C = data.calibrate,
M = data.getmeta, IMP)




