library(GGIR)


### Name: g.impute
### Title: function to identify invalid periods in the meta-data as
###   generated by g.getmeta and to impute these invalid periods with the
###   average of similar timepoints on other days of the measurement
### Aliases: g.impute

### ** Examples

## Not run: 
##D   #inspect file:
##D   I = g.inspectfile(datafile)
##D   
##D   #autocalibration:
##D   C = g.calibrate(datafile) 
##D   
##D   #get meta-data:
##D   M = g.getmeta(datafile)
## End(Not run)

data(data.getmeta)
data(data.inspectfile)

#impute meta-data:
IMP = g.impute(M=data.getmeta, I=data.inspectfile)




