library(MortalityTables)


### Name: mortalityTable.ageShift-class
### Title: Class mortalityTable.ageShift - Cohort life tables generated by
###   age-shift
### Aliases: mortalityTable.ageShift-class mortalityTable.ageShift

### ** Examples

mortalityTables.load("Austria_Annuities_AVOe2005R")
tb = mortalityTable.ageShift(
    ages = ages(AVOe2005R.male),
    deathProbs = deathProbabilities(AVOe2005R.male, YOB = 1992),
    ageShifts = generateAgeShift(1, c(1962, 1985, 2000, 2015, 2040, 2070)))
# The cohort tables for different birth years are just the base probabilities with modified ages
plot(getCohortTable(tb, YOB = 1963), getCohortTable(tb, YOB = 2017))




