library(IndTestPP)


### Name: DepNHNeyScot.fun
### Title: Generates trajectories of dependent Neyman-Scott cluster
###   processes
### Aliases: DepNHNeyScot.fun GenSons.fun

### ** Examples

# Generation of three dependent Neyman-Scott processes with  the same mean number
#of sons per cluster and locations generated by the same normal distribution

set.seed(123)
lambdaParent<-runif(100,0,0.1)

DepNHNeyScot.fun(lambdaParent=lambdaParent, d=3, lambdaNumP = 2,
	 dist = "normal", sigmaC = 3,fixed.seed=123)




