library(gdimap)


### Name: niinorm
### Title: Normalization of Principal Diffusion Directions
### Aliases: niinorm
### Keywords: utilities

### ** Examples

## Not run: 
##D ## Example using the PDD files in gdimap
##D ## normalize vector data generated by vMF functions
##D ## before visualization with FSL/fslview
##D fi1 <- "data_V1.nii.gz"
##D p <- system.file(file.path("extdata", fi1), package = "gdimap")
##D p1 <- strsplit(p,fi1)[[1]][1]
##D niinorm(srcdir=p1, filename=fi1, savedir=tempdir())
##D fi2 <- "data_V2.nii.gz"
##D niinorm(srcdir=p1, filename=fi2, savedir=tempdir())
##D ## try fslview if installed
##D fo1 <- file.path(tempdir(),"data_V1n.nii.gz")
##D fo2 <- file.path(tempdir(),"data_V2n.nii.gz")
##D fo3 <- file.path(p1, "data_gfa.nii.gz")
##D if(Sys.which("fslview") != "") system(paste("fslview", fo3, fo2, fo1, "&"))
## End(Not run)



