library(gdimap)


### Name: rgbvolmap
### Title: Generalized Fractional Anisotropy (GFA) Maps (RGB Maps)
### Aliases: rgbvolmap
### Keywords: dplot

### ** Examples

## Not run: 
##D     ##-------------
##D     ## Generate ODF volumes (GQI volume processing) for
##D     ## range of slices using deterministic find peaks algorithm
##D     gqi.odfpeaks(rg=c(1,1), showglyph=FALSE)
##D     ## Show RGB maps for range of slices processed by gqi.odfpeaks()
##D     rgbvolmap(fbase=tempdir(), rg=c(1,1))
##D     ## Changing background colour
##D     rgbvolmap(fbase=tempdir(), rg=c(1,1), bg="transparent")
##D     ##-------------
##D     ## Process whole volume: generates NIfTI files
##D     ##   data_gfa_gqi.nii.gz and data_V1_gqi.nii.gz
##D     gqi.odfpeaks(rg=NULL)
##D     ## Visualization of RBG maps generated by vMF function "gqi.odfvmf"
##D     ## (cf. FSL/fslview tool) 
##D     rgbvolmap(fbase=tempdir(), rg=NULL, bview="coronal")
## End(Not run)



