library(plfm)


### Name: print.bayesplfm
### Title: Printing 'bayesplfm' objects
### Aliases: print.bayesplfm

### ** Examples


## Not run: 
##D ##load car data
##D data(car)
##D 
##D 
##D ## Compute a sample of the posterior distribution 
##D ## for the disjunctive model with two features
##D ## compute the starting point using plfm
##D carbayes2<-bayesplfm(maprule="disj",freq1=car$freq1,freqtot=car$freqtot,F=2,
##D                       maxNiter=500,Nburnin=0,Nstep=100,Nchains=2,
##D                       start.bayes="best")
##D 
##D 
##D ## print the object generated by bayesplfm
##D carbayes2
## End(Not run)




