library(plfm)


### Name: summary.bayesplfm
### Title: Summarizing Bayesian probabilistic latent feature analysis
### Aliases: summary.bayesplfm

### ** Examples

## Not run: 
##D 
##D ##load car data
##D data(car)
##D 
##D ## compute 5 runs of disjunctive model with 2 features
##D carem2<-plfm(maprule="disj",freq1=car$freq1,freqtot=car$freqtot,F=2,M=5)
##D 
##D ## Compute a sample of the posterior distribution 
##D ## for the disjunctive model with two features
##D ## use the posterior mode obtained with the previous plfm analysis
##D carbayes2<-bayesplfm(maprule="disj",freq1=car$freq1,freqtot=car$freqtot,F=2,
##D                       maxNiter=500,Nburnin=0,Nstep=100,Nchains=2,
##D                       start.bayes="fitted.plfm",fitted.plfm=carem2)
##D 
##D 
##D ## compute a summary of the object generated by bayesplfm
##D summarycarbayes2<-summary(carbayes2)
## End(Not run)



