library(delt)


### Name: partition
### Title: Finds the partition generated by an evaluation tree
### Aliases: partition
### Keywords: hplot

### ** Examples

library(denpro)
dendat<-sim.data(n=100,seed=5,type="mulmodII")
et<-densplit(dendat)

pa<-partition(et)

plotparti(pa)




