library(rstan)


### Name: traceplot
### Title: Markov chain traceplots
### Aliases: traceplot traceplot,stanfit-method
### Keywords: methods

### ** Examples
## Not run: 
##D # Create a stanfit object from reading CSV files of samples (saved in rstan
##D # package) generated by funtion stan for demonstration purpose from model as follows. 
##D # 
##D excode <- '
##D   transformed data {
##D     real y[20];
##D     y[1] <- 0.5796;  y[2]  <- 0.2276;   y[3] <- -0.2959; 
##D     y[4] <- -0.3742; y[5]  <- 0.3885;   y[6] <- -2.1585;
##D     y[7] <- 0.7111;  y[8]  <- 1.4424;   y[9] <- 2.5430; 
##D     y[10] <- 0.3746; y[11] <- 0.4773;   y[12] <- 0.1803; 
##D     y[13] <- 0.5215; y[14] <- -1.6044;  y[15] <- -0.6703; 
##D     y[16] <- 0.9459; y[17] <- -0.382;   y[18] <- 0.7619;
##D     y[19] <- 0.1006; y[20] <- -1.7461;
##D   }
##D   parameters {
##D     real mu;
##D     real<lower=0, upper=10> sigma;
##D     vector[2] z[3];
##D     real<lower=0> alpha;
##D   } 
##D   model {
##D     y ~ normal(mu, sigma);
##D     for (i in 1:3) 
##D       z[i] ~ normal(0, 1);
##D     alpha ~ exponential(2);
##D   } 
##D '
##D # exfit <- stan(model_code = excode, save_dso = FALSE, iter = 200, 
##D #               sample_file = "rstan_doc_ex.csv")
##D # 
##D exfit <- read_stan_csv(dir(system.file('misc', package = 'rstan'),
##D                        pattern='rstan_doc_ex_[[:digit:]].csv',
##D                        full.names = TRUE))
##D 
##D print(exfit)
##D traceplot(exfit)
##D traceplot(exfit, size = 0.25)
##D traceplot(exfit, pars = "sigma", inc_warmup = TRUE)
##D 
##D trace <- traceplot(exfit, pars = c("z[1,1]", "z[3,1]"))
##D trace + scale_color_discrete() + theme(legend.position = "top")
## End(Not run)



