library(rstan)


### Name: read_stan_csv
### Title: Read CSV files of samples generated by (R)Stan into a 'stanfit'
###   object
### Aliases: read_stan_csv

### ** Examples

csvfiles <- dir(system.file('misc', package = 'rstan'),
                pattern = 'rstan_doc_ex_[0-9].csv', full.names = TRUE)
fit <- read_stan_csv(csvfiles)



