library(rstan)


### Name: stanfit-class
### Title: Class 'stanfit': fitted Stan model
### Aliases: stanfit-class stanfit show,stanfit-method get_cppo_mode
###   get_cppo_mode,stanfit-method get_stancode get_stancode,stanfit-method
###   get_stanmodel get_stanmodel,stanfit-method get_seed
###   get_seed,stanfit-method get_seeds get_seeds,stanfit-method get_inits
###   get_inits,stanfit-method get_posterior_mean
###   get_posterior_mean,stanfit-method get_elapsed_time
###   get_elapsed_time,stanfit-method get_logposterior
###   get_logposterior,stanfit-method get_adaptation_info
###   get_adaptation_info,stanfit-method get_sampler_params
###   get_sampler_params,stanfit,logical-method
### Keywords: classes

### ** Examples
## Not run: 
##D showClass("stanfit")
##D ecode <- '
##D   parameters {
##D     real<lower=0> y[2];
##D   } 
##D   model {
##D     y ~ exponential(1);
##D   }
##D '
##D fit <- stan(model_code = ecode, iter = 10, chains = 1)
##D fit2 <- stan(fit = fit)
##D print(fit2)
##D plot(fit2)
##D traceplot(fit2)
##D ainfo <- get_adaptation_info(fit2)
##D cat(ainfo[[1]])
##D seed <- get_seed(fit2)
##D sp <- get_sampler_params(fit2)
##D sp2 <- get_sampler_params(fit2, inc_warmup = FALSE)
##D head(sp[[1]])
##D 
##D lp <- log_prob(fit, c(1, 2))
##D grad <- grad_log_prob(fit, c(1, 2))
##D lp2 <- attr(grad, "log_prob") # should be the same as "lp"
##D 
##D # get the number of parameters on the unconstrained space
##D n <- get_num_upars(fit)
##D 
##D # parameters on the positive real line (constrained space) 
##D y1 <- list(y = rep(1, 2)) 
##D 
##D uy <- unconstrain_pars(fit, y1) 
##D ## uy should be c(0, 0) since here the log transformation is used
##D y1star <- constrain_pars(fit, uy)
##D 
##D print(y1)
##D print(y1star) # y1start should equal to y1 
## End(Not run)

# Create a stanfit object from reading CSV files of samples (saved in rstan
# package) generated by funtion stan for demonstration purpose from model as follows. 
# 
excode <- '
  transformed data {
    real y[20];
    y[1] <- 0.5796;  y[2]  <- 0.2276;   y[3] <- -0.2959; 
    y[4] <- -0.3742; y[5]  <- 0.3885;   y[6] <- -2.1585;
    y[7] <- 0.7111;  y[8]  <- 1.4424;   y[9] <- 2.5430; 
    y[10] <- 0.3746; y[11] <- 0.4773;   y[12] <- 0.1803; 
    y[13] <- 0.5215; y[14] <- -1.6044;  y[15] <- -0.6703; 
    y[16] <- 0.9459; y[17] <- -0.382;   y[18] <- 0.7619;
    y[19] <- 0.1006; y[20] <- -1.7461;
  }
  parameters {
    real mu;
    real<lower=0, upper=10> sigma;
    vector[2] z[3];
    real<lower=0> alpha;
  } 
  model {
    y ~ normal(mu, sigma);
    for (i in 1:3) 
      z[i] ~ normal(0, 1);
    alpha ~ exponential(2);
  } 
'

# exfit <- stan(model_code = excode, save_dso = FALSE, iter = 200, 
#               sample_file = "rstan_doc_ex.csv")
# 

exfit <- read_stan_csv(dir(system.file('misc', package = 'rstan'),
                       pattern='rstan_doc_ex_[[:digit:]].csv',
                       full.names = TRUE))

print(exfit)
## Not run: 
##D plot(exfit)
## End(Not run)

adaptinfo <- get_adaptation_info(exfit)
inits <- get_inits(exfit) # empty
inits <- get_inits(exfit, iter = 101)
seed <- get_seed(exfit)
sp <- get_sampler_params(exfit)
ml <- As.mcmc.list(exfit)
cat(get_stancode(exfit))



