library(CombinePValue)


### Name: selfcontained.test
### Title: selfcontained.test: combine a vector of correlated p-values
### Aliases: selfcontained.test selfcontained.test
### Keywords: package

### ** Examples

#p_permu is generated by bootstrap or permutation to estimate correlations among p values.   

a<-matrix(c(0.02,0.06,0.07,0.01,0.02,0.09,0.01,0.01,0.10,0.12,0.14,0.07,0.09,0.10,0.15),nrow=3) 
selfcontained.test(pvalue=c(0.01,0.04,0.06),weight=NA,p_permu=a) 

#The traditional Fisher's test assuming p-values are independent. 

selfcontained.test(pvalue=c(0.01,0.04,0.06),weight=NA,p_permu=NA) 

#Generalized Fisher method with a weight function.  If p_permu=NA, then p-values are independent.

selfcontained.test(pvalue=c(0.01,0.04,0.06),weight=c(7,2,1.5),p_permu=NA) 
 



