library(HelpersMG)


### Name: logLik.LD50
### Title: Return Log Likelihood of a fit generated by LD50
### Aliases: logLik.LD50

### ** Examples

## Not run: 
##D data <- data.frame(Doses=c(80, 120, 150, 150, 180, 200),
##D Alive=c(10, 12, 8, 6, 2, 1),
##D Dead=c(0, 1, 5, 6, 9, 15))
##D LD50_logistic <- LD50(data, equation="logistic")
##D logLik(LD50_logistic)
##D AIC(LD50_logistic)
## End(Not run)



