library(spant)


### Name: read_tqn_fit
### Title: Reader for csv fit results generated by TARQUIN.
### Aliases: read_tqn_fit

### ** Examples

## Not run: 
##D fit <- read_tqn_fit(system.file("extdata","fit.csv",package="spant"))
## End(Not run)



