library(geotopbricks)


### Name: read.vectorized.geotop.recovery
### Title: Reads a text file like the one generated by
###   'write.vectorized.geotop.recovery'
### Aliases: read.vectorized.geotop.recovery

### ** Examples

# see the examples of read.ascii.vectorized.brick



