library(abcdeFBA)


### Name: flux_difference_plotter
### Title: flux_difference_plotter, a function to plot two pre-existing
###   flux distributions obtained using FBA_solve
### Aliases: flux_difference_plotter 'flux distribution comparisons'

### ** Examples

# A comparison of two flux distributions generated by FBA_solve
data(Ecoli_core)

#The reaction number for O2 exchange is 36 by setting 
#the corresponding bounds to zero we make a aerobic 
#respiration deficient mutant
	
Ec_Mutant<-CHANGE_RXN_BOUNDS(36,Ecoli_core,0,0)

mut_flux<-FBA_solve(Ec_Mutant)
wt_flux<-FBA_solve(Ecoli_core)

#flux_difference_plotter(wt_flux,mut_flux,Ecoli_core,
#graph_fname="Flux_comparison")



