library(abcdeFBA)


### Name: Sybil_2_FBA_obj
### Title: Sybil_2_FBA_obj, a function to convert a model generated by
###   Sybil into the one used by abcdeFBA.
### Aliases: Sybil_S4_object SBML Sybil_2_FBA_obj

### ** Examples

#Model conversion
#data(Ecoli_core) - # the Ecoli_core model included in the Sybil package
#FBA_obj<-Sybil_2_FBA_obj(Ecoli_core)



