library(tstools)


### Name: read_swissdata
### Title: Read data generated by the Swissdata project
### Aliases: read_swissdata

### ** Examples

ds_location <- system.file("example_data/ch.seco.css.csv",package = "tstools")
tslist <- read_swissdata(ds_location,"idx_type")
tsplot(tslist[1])



