library(LRcontrast)


### Name: pLRcontrast
### Title: Simulate p-values for LR contrast tests in regression models
###   with a lack of identifiability.
### Aliases: pLRcontrast
### Keywords: ~kwd1 ~kwd2

### ** Examples

# In this case the data is generated by the constant model, i.e. the 
# null hypothesis of no dose response is true.

resp <- rnorm(n = 50, mean = 0.2)
dose <- c(rep(0, 10), rep(0.05, 10), rep(0.2, 10), rep(0.6, 10), rep(1, 10))

# Calculate the p-values in this scenario
			 
pLRcontrast(dose = dose, resp = resp, models = c("linear", "emax", 
            "exponential", "linlog"), nsim = 10)



