library(wavethresh)


### Name: wr3D
### Title: Inverse DWT for 3D DWT object.
### Aliases: wr3D
### Keywords: smooth nonlinear

### ** Examples

#
# Now let's take the object generated by the last stage in the EXAMPLES
# section of threshold.wd3D and invert it!
#
#testwr <- wr3D(testwd3DT)
#
# You'll find that testwr is an array of dimension 8x8x8!
#



