library(PROSPER)


### Name: sel_resist
### Title: Calculating resistance values
### Aliases: sel_resist

### ** Examples

#dfgenotype is usually generated by the function 'struc_preparation'.
#Here, a simple example is done by hand.
var1 <- c("00","01","02","10","11","12","20","21","21")
var2 <- c(0,0,0,1,1,1,2,2,2)
var3 <- c(0,1,2,0,1,2,0,1,2)
dfgenotype <- data.frame(genotype=var1,l1=var2,l2=var3)
sel_resist(Rmx=10, epis=0, dom=1)



