library(qmrparser)


### Name: pcAxisParser
### Title: Parser for PC-AXIS format files
### Aliases: pcAxisParser
### Keywords: PC-AXIS

### ** Examples


  ## Not run: 
##D     ## significant time reductions may be achieve by doing:
##D     library("compiler")
##D     enableJIT(level=3)
##D   
## End(Not run)

  name     <- system.file("extdata","datInSFexample6_1.px", package = "qmrparser")
  stream   <- streamParserFromFileName(name,encoding="UTF-8")
  cstream  <-  pcAxisParser(stream)
  if ( cstream$status == 'ok' ) {
    
    ## HEADING 
    print(Filter(function(e) e$keyword=="HEADING",cstream$node)[[1]] $ruleRight$value)  
  
    ## STUB
    print(Filter(function(e) e$keyword=="STUB",cstream$node)[[1]] $ruleRight$value)  
  
    ## DATA
    print(Filter(function(e) e$keyword=="DATA",cstream$node)[[1]] $ruleRight$value)
    
  }

  ## Not run: 
##D       #
##D       # Error messages like
##D       #                " ... invalid multibyte string ... "
##D       # or warnings
##D       #                " input string ...  is invalid in this locale"
##D       #
##D       # For example, in Linux the error generated by this code:
##D        name     <-     "http://www.ine.es/pcaxisdl//t20/e245/p04/a2009/l0/00000008.px" 
##D       stream   <- streamParserFromString( readLines( name ) )    
##D       cstream  <- pcAxisParser(stream)
##D       if ( cstream$status == 'ok' )  cube <- pcAxisCubeMake(cstream)
##D       #
##D       # is caused by files with a non-readable 'encoding'.
##D       # In the case where it could be read, there may also be problems 
##D       # with string-handling functions, due to multibyte characters. 
##D       # In Windows, according to \code{link{Sys.getlocale}()},
##D       # file may be read but accents, ñ, ... may not be correctly recognised.
##D       #
##D       #
##D       # There are, at least, the following options:
##D       #  - File conversion to utf-8, from the OS, with
##D       # "iconv - Convert encoding of given files from one encoding to another"
##D       #
##D       #  - File conversion in R:
##D       name    <- "http://www.ine.es/pcaxisdl//t20/e245/p04/a2009/l0/00000008.px" 
##D       stream   <- streamParserFromString( iconv( readLines( name ), "IBM850", "UTF-8") )
##D       cstream  <- pcAxisParser(stream)
##D       if ( cstream$status == 'ok' )  cube <- pcAxisCubeMake(cstream)
##D       #
##D       # In the latter case, latin1 would also work, but accents, ñ, ... would not be correctly read.
##D       #
##D       #  - Making the assumption that the file does not contain multibyte characters:
##D       #
##D       localeOld <- Sys.getlocale("LC_CTYPE")
##D       Sys.setlocale(category = "LC_CTYPE", locale = "C")
##D       #
##D       name     <-
##D         "http://www.ine.es/pcaxisdl//t20/e245/p04/a2009/l0/00000008.px" 
##D       stream   <- streamParserFromString( readLines( name ) )
##D       cstream  <- pcAxisParser(stream)
##D       if ( cstream$status == 'ok' )  cube <- pcAxisCubeMake(cstream)
##D       #
##D       Sys.setlocale(category = "LC_CTYPE", locale = localeOld)
##D       #
##D       # However, some characters will not be correctly read (accents, ñ, ...)
##D 
##D     
## End(Not run)




