library(dataone)


### Name: generateIdentifier
### Title: Get a unique identifier that is generated by the Member Node
###   repository and guaranteed to be unique.
### Aliases: generateIdentifier enerateIdentifier
###   generateIdentifier,MNode-method

### ** Examples

## Not run: 
##D library(dataone)
##D cn <- CNode("STAGING")
##D mn <- getMNode(cn, "urn:node:mnStageUCSB2")
##D newid <- generateIdentifier(mn, "UUID")
## End(Not run)



