library(NPCD)


### Name: ModelFit
### Title: Compute overall model fit statistics for outputs generated by
###   estimation functions in the package
### Aliases: ModelFit

### ** Examples

# See examples in ParMLE and JMLE.



