library(BayLum)


### Name: Age_Computation
### Title: Bayesian analysis for the OSL age estimation of one sample
### Aliases: Age_Computation

### ** Examples

## load data file generated by the function Generate_DataFile
data(DATA1,envir = environment())
priorage <- c(10,60) # GDB3 is an old sample
Age <- Age_Computation(
 DATA = DATA1,
 SampleName = "GDB3",
 PriorAge = priorage,
 Iter = 100,
 quiet = TRUE)




