library(BayLum)


### Name: combine_DataFiles
### Title: Combine objects generated by Generate_DataFile and
###   Generate_DataFile_MG
### Aliases: combine_DataFiles Concat_DataFile

### ** Examples

# load data files
data(DATA1,envir = environment())
data(DATA2,envir = environment())

#combine objects
DATA3 <- combine_DataFiles(DATA1, DATA2)
str(DATA3)



