library(BayLum)


### Name: LT_RegenDose
### Title: Plots Lx/Tx as a function of the regenerative dose
### Aliases: LT_RegenDose

### ** Examples

## load data file generated by the function Generate_DataFile
data(DATA3,envir = environment())
path<- system.file("extdata/FER1", "", package="BayLum")
folder=""
samplename="FER1"
LT_RegenDose(DATA=DATA3,Path=path,FolderNames=folder,SampleNames=samplename,Nb_sample=1,SG=FALSE)



