library(abc)


### Name: summary.abc
### Title: Summaries of posterior samples generated by ABC algortithms
### Aliases: summary.abc getmode
### Keywords: htest models

### ** Examples

## see ?abc for examples



