library(mkin)


### Name: plot.mmkin
### Title: Plot model fits (observed and fitted) and the residuals for a
###   row or column of an mmkin object
### Aliases: plot.mmkin

### ** Examples

  # Only use one core not to offend CRAN checks, use Levenberg-Marquardt for speed
  fits <- mmkin(c("FOMC", "HS"), 
                list("FOCUS B" = FOCUS_2006_B, "FOCUS C" = FOCUS_2006_C), # named list for titles
                cores = 1, quiet = TRUE, method.modFit = "Marq")
  plot(fits[, "FOCUS C"])
  plot(fits["FOMC", ])

  # We can also plot a single fit, if we like the way plot.mmkin works, but then the plot
  # height should be smaller than the plot width (this is not possible for the html pages
  # generated by pkgdown, as far as I know).
  plot(fits["FOMC", "FOCUS C"]) # same as plot(fits[1, 2])



