library(MCMCvis)


### Name: MCMCtrace
### Title: Trace and density plots from MCMC output
### Aliases: MCMCtrace

### ** Examples

#Load data
data(MCMC_data)

#Traceplots for all 'beta' parameters - a pdf of the traceplots is generated by default
MCMCtrace(MCMC_data, params = 'beta', pdf = FALSE)

#Traceplots (individual density lines for each chain) just for 'beta[1]'
#'params' takes regular expressions when ISB = FALSE, square brackets must be escaped with '\\'
MCMCtrace(MCMC_data, params = 'beta\\[1\\]', ISB = FALSE, ind = TRUE, pdf = FALSE)

#Plot prior on top of posterior, calculate prior/posterior overlap (PPO) just for 'beta[1]'
#Add Rhat and n.eff values to density plots
#'params' takes regular expressions when ISB = FALSE, square brackets must be escaped with '\\'
PR <- rnorm(15000, 0, 32)
MCMCtrace(MCMC_data, params = 'beta\\[1\\]', ISB = FALSE, priors = PR, 
pdf = FALSE, Rhat = TRUE, n.eff = TRUE)




