library(EnsCat)


### Name: Benhc
### Title: Performs bootstrap ensemble hierarchical clustering for
###   categorical data.
### Aliases: Benhc
### Keywords: lowdimension

### ** Examples

#data('zoo')
### zoo includes the zoo data downloaded from UCI
### Machine Learning Repository
### Calculate ensemble dissimilarities with 150 ensemble members
#disten<-Benhc(zoo$obs,En=150)
### This function performs a hierarchical cluster analysis using
### dissimilarities obtained by the ensembling procedure in Benhc
#en<-hclust(disten,method='average')
### A plot of the dendrogram can be generated by
#plot(en,label=zoo$lab)



