library(phenology)


### Name: logLik.phenology
### Title: Return Log Likelihood of a fit generated by fit_phenology
### Aliases: logLik.phenology

### ** Examples

## Not run: 
##D library(phenology)
##D data(result_Gratiot)
##D logLik(result_Gratiot)
##D AIC(result_Gratiot)
## End(Not run)



