library(phenology)


### Name: logLik.Tagloss
### Title: Return Log Likelihood of a fit generated by Tagloss_fit
### Aliases: logLik.Tagloss

### ** Examples

## Not run: 
##D library(phenology)
##D # Example
##D data_f_21 <- Tagloss_format(outLR, model="21")
##D # Without the N20 the computing is much faster
##D data_f_21_fast <- subset(data_f_21, subset=(is.na(data_f_21$N20)))
##D par <- structure(c(48.8292784204825, 1039.02842229274, -89.3162940697861, 
##D 5.21817463244988, 8.00575451188548, 8.32971268127933, 161.265553603601, 
##D 602.935748681661, 2643.57415102633, 16.752815732218, 10.181616195839, 
##D 7.14279063312016), .Names = c("D1_2", "D2D1_2", "D3D2_2", "A_2", 
##D "B_2", "C_2", "D1_1", "D2D1_1", "D3D2_1", "A_1", "B_1", "C_1"))
##D o <- Tagloss_fit(data=data_f_21_fast, fitted.parameters=par)
##D logLik(o)
##D AIC(o)
## End(Not run)



